### ISSUE TITLE
Server crashing after choosing .stay / swap.

### ISSUE THREAD

**Issue by yuvali1337** [splewis/csgo-pug-setup#103]
I am hosting an server with this plugin.
works perfect.
except the fact that server crashing then im enabling the knife round
after the knife round,
then i have an option .stay / .swap

im typing .stay / swap
baum no server5u
i cri evry die
pls

**Comment by ixayldz** [comment]
Hi lewis Can you add me on steam i need ask something thanks.

http://steamcommunity.com/id/jesustar/

**Comment by splewis** [comment]
Can you post the output of:

``meta version``, ``sm version``, and ``sm plugins list`` so I know what versions of sourcemod, metamod, and pugsetup your using?

**Comment by yuvali1337** [comment]
Sourcemod — 1.7.3-dev
Meta - 1.10.6
http://prntscr.com/8w7hml
Plugins

**Comment by splewis** [comment]
It's probably either the knife or weapons skin plugins causing it, which are already a bad idea to use.

**Comment by yuvali1337** [comment]
How is that causing it.. :-1:

**Comment by splewis** [comment]
You'd have to ask a Valve developer. 

Let me know if you can reproduce a crash without those plugins, otherwise it's not an bug with this plugin as far as I'm concerned.
