### ISSUE TITLE
Is it possible to use other gamemodes on server besides comp that installed this plugin?

### ISSUE THREAD

**Issue by endersodium** [splewis/csgo-pug-setup#110]
I tried in different ways but no matter how I set game_mode and game_type it will be locked in competitive. Sometimes I need this server for other usages.

**Comment by splewis** [comment]
I don't understand what the issue is. Unless you type .setup or explicitly turned on the autosetup option this plugin has no effect on the server.

**Comment by HalfEatenPie** [comment]
The way this plugin works is that after you type .setup and everything's configured, the plugin then executes a series of scripts which configures the server.  You can find these scripts in cfg/sourcemod/pugsetup/.  Scripts such as live.cfg are executed during a live game, warmup.cfg is executed during warmup, etc.  

There's nothing in the plugin that prevents you from using other game modes or game types.  I'd suggest you look up this article: https://developer.valvesoftware.com/wiki/Counter-Strike:_Global_Offensive_Dedicated_Servers to get a better understanding how a server functions.  This plugin doesn't conflict with other game modes or game types.

**Comment by endersodium** [comment]
Maybe I should look over my settings again. I submitted this was because that I only have sourcemod and this plugin on my server and no matter how I change the game_type and game_mode params the game just seemed locked in comp mode. When I tried deathmatch I couldn't choose any weapon and it showed I have $800 initial money.

**Comment by HalfEatenPie** [comment]
I'd suggest you check your launch parameters of the server.  If you're using a pre-made script distributed by some other people, they might have pre-coded in the competitive game type and mode.

**Comment by endersodium** [comment]
After I tried few times it works but just btw I don't know why I already have the knife config in my configs folder but the knife round will still give players pistols which is an issue for me.

**Comment by HalfEatenPie** [comment]
What do you mean you already have the knife config in your configs.  Where is it located?

The knife round config should be located in /cfg/sourcemod/pugsetup/life.cfg.  I'd double check to make sure some other config files aren't messing with it.  It seems you're having overlapping cvars in my opinion.
