### ISSUE TITLE
sm_kick does autoretry!?

### ISSUE THREAD

**Issue by KuNh4** [splewis/csgo-pug-setup#117]
When you kick someone via the sourcemod admin menu, it will kick the player but at same time the played will be reconnected. 

It has to be a issue with pug setup.

**Comment by splewis** [comment]
That's very unlikely. What version of sourcemod are you using (sm version in console will tell you)?

**Comment by KuNh4** [comment]
SourceMod 1.7.3 build 5275

**Comment by splewis** [comment]
My only suggestion would be to try updating it to a more recent snapshot, then. sm_kick has nothing to do with pugsetup.

**Comment by splewis** [comment]
I've noticed this issue elsewhere not using pugsetup since a recent update: [this thread](https://forums.alliedmods.net/showthread.php?t=276790) and on ESEA servers when players get kicked when a match fails to start. It's a Valve/SM issue.
