### ISSUE TITLE
[Suggestion] Auto-Ready

### ISSUE THREAD

**Issue by KuNh4** [splewis/csgo-pug-setup#118]
Could you please add a convar to disable the .ready or make the players auto-ready upon entering on the server? Or add to the .setup options a option to Ask Ready, or Auto-Ready. This would allow auto-mixing without input from someone with permissions ;)

EDIT - This would allow auto-mixing without input from someone with permissions, or the 10 players typing .ready in the chat (which is a bit lame, cuz sometimes someone might AFK or trolls the rest of other people waiting to start their game).

Thanks for your work m8 :+1: :)

**Comment by splewis** [comment]
It doesn't make sense to me to have this option.

You can already "auto-mix" with the autosetup cvar ``pugsetup_autosetup 1``.

the autokicker plugin also has a ``sm_pugsetup_autokicker_ready_time`` cvar to kick people if they don't ready up.

**Comment by KuNh4** [comment]
The word "auto" counts for something I presume. Asking user to type .ready goes against the "automatic" mix setup :(

I knew about the pugsetup_autosetup 1 , but I did not knew about the ready time, but still it will kick the user. Why not force users ready, because public automix servers will always have someone to f... with the others. Unfortunately kicking will not solve the issue.

I am just suggesting, I would do it myself If I knew it.

Regards

**Comment by splewis** [comment]
If someone refuses to ready up in order to troll, I think there are bigger issues to deal with. 

I don't think it makes sense to add this here, but there is a ``ReadyPlayer`` [native](https://github.com/splewis/csgo-pug-setup/blob/master/scripting/include/pugsetup.inc#L212) if someone really wants to have an auto-ready feature for their server(s).
