### ISSUE TITLE
Damageprint color doesn't work for me

### ISSUE THREAD

**Issue by control99** [splewis/csgo-pug-setup#119]
when adding this code < https://github.com/splewis/csgo-pug-setup/blob/9a6a4a0e721706e50df59fa2b4d9227922bc04b1/scripting/pugsetup_damageprint.sp > to pugsetup_damageprint.sp the color does not appear in chat when round ends. Pls help

**Comment by splewis** [comment]
I'm not sure what you're doing. Are you editing the plugin? You could just use the [latest release](https://github.com/splewis/csgo-pug-setup/releases/tag/1.4.3) and turn on sm_pugsetup_damageprint_auto_color in cfg/sourcemod/pugsetup/pugsetup_damageprint.cfg.

**Comment by control99** [comment]
i copied this to https://github.com/splewis/csgo-pug-setup/blob/9a6a4a0e721706e50df59fa2b4d9227922bc04b1/scripting/pugsetup_damageprint.sp to the 
pugsetup_damageprint.sp in the server

**Comment by control99** [comment]
also tried it will with the new update and still doesn't work

**Comment by splewis** [comment]
It doesn't matter if you upload the source code for it to the server. All that matters is the plugin binary (.smx) file being  in the addons/sourcemod/plugins directory. In the release downloads, it is in the plugins/disabled directory, so you'd have to move it up a directory.

**Comment by control99** [comment]
did that and still dont show colors

**Comment by splewis** [comment]
Well the plugin doesn't apply any colors by default.

Are you changing the sm_pugsetup_damageprint_auto_color or sm_pugsetup_damageprint_format cvars at all?

**Comment by control99** [comment]
i changed it sm_pugsetup_damageprint_auto_color 1 and left the format as this
("sm_pugsetup_damageprint_format", "--> ({DMG_TO} dmg / {HITS_TO} hits) to ({DMG_FROM} dmg / {HITS_FROM} hits) from {NAME} ({HEALTH} HP)"

**Comment by splewis** [comment]
It works for me. http://imgur.com/OI3VVbe

Can you post the plugin list on the server? (``sm plugins`` in console)

**Comment by control99** [comment]
http://imgur.com/N2fe6TF the plugins on the server

**Comment by BarclayTech** [comment]
It works fine for me too, FYI.

Just moved the .smx from disabled to main folder.

**Comment by control99** [comment]
i did that and still dont work

**Comment by control99** [comment]
it works now, all i did was wipe the server settings and reinstall pug setup, enable the convar in sp file and cfg file. thanks for your time splewis in helping
