### ISSUE TITLE
MySQL support on RWS?

### ISSUE THREAD

**Issue by iDentity1337** [splewis/csgo-pug-setup#120]
Is there an MySQL support for the RWS Stats?

**Comment by splewis** [comment]
No. There used to be, but it was very buggy so it was removed.

**Comment by iDentity1337** [comment]
Yeah I spotted it in older branches. What were the bugs?

**Comment by splewis** [comment]
https://github.com/splewis/csgo-pug-setup/blob/1.3.1/scripting/pugsetup_rwsbalancer.sp

It just didn't consistently fetch & save to the correct source decided from sm_pugsetup_rws_storage_method.

**Comment by iDentity1337** [comment]
Can't even seem to compile this one.

**Comment by MajorErection** [comment]
if not mysql, how is the rws stored?

**Comment by MajorErection** [comment]
Nevermind, I got it already.
