### ISSUE TITLE
stats

### ISSUE THREAD

**Issue by ixayldz** [splewis/csgo-pug-setup#123]
myfriend i have to tell this is best pug plugin. Just can you tell me how we send to sql match stats ?

when match finish i want send to players kill deaths etc.. to sql... show us 1 way pls

**Comment by BarclayTech** [comment]
As far as I know, at this moment in time the plugin doesn't do this.

Warmod does and is probably better if you're wanting to track this kind of information.

Pugsetup is the simple and sweet alternative.

**Comment by splewis** [comment]
I might make a stats plugin, but if I do it will be separate from pugsetup. Presumably it would just require pugsetup to tell it when to start and stop recording stats + some metadata.
