### ISSUE TITLE
Any way to execute a command on match end?

### ISSUE THREAD

**Issue by dechristopher** [splewis/csgo-pug-setup#124]
I'd like to have a system in place in which I can execute a command when the match ends to shut down the server. I have a script in place to restart the server on shutdowns, but I can find no way to actually shut down the server on match end. I'm making an automated PUG system with this plugin and kicking players off a server after they play is a must.

Any help with this would be appreciated.

**Comment by splewis** [comment]
You can use the ``OnMatchOver`` forward in another plugin. That plugin would either shut the server down or expose that it should be shut down to another system.

**Comment by dechristophera** [comment]
Thanks for the quick response, is the OnMatchOver forwarded from pugsetup or is it native to sourcemod?

**Comment by splewis** [comment]
From pugsetup.

https://github.com/splewis/csgo-pug-setup/blob/1.4.3/scripting/include/pugsetup.inc#L125

**Comment by dechristophera** [comment]
Thanks, I appreciate it!

**Comment by splewis** [comment]
On another note, if you're trying to make an automated system the other project I recently started working on might be worth looking at: https://github.com/splewis/get5

(it already kicks users when a match is over)

**Comment by dechristophera** [comment]
I've actually browsed that project in the past. Does it allow for random steamIDs to join and load up a game or would I have to generate a match file before everyone joined?

**Comment by splewis** [comment]
(for the record: it's less than a week old while pugsetup goes back 2 years)

You could have it in a warmup state until 10 join, then generate the match as long as ``get5_kick_when_no_match_loaded`` is 0.

**Comment by dechristophera** [comment]
Yeah I noticed it was a brand new plugin. And can the plugin generate the match by itself or will I need to implement a system in my backend to generate it myself?

**Comment by splewis** [comment]
You'd have to create that system yourself.

**Comment by dechristophera** [comment]
That's fine then. And mind filling me in on a few details? Can players join before a match is generated? And would it be possible for you to add a cvar to pugsetup to enable / disable kicking on the match end? I feel like implementing a new plugin might make more challenges for me in the long run. PugSetup has been our go-to and it has quite literally EVERY feature we need other than kicking on match end.

**Comment by splewis** [comment]
> Can players join before a match is generated? 

Depends on ``get5_kick_when_no_match_loaded`` 

> And would it be possible for you to add a cvar to pugsetup to enable / disable kicking on the match end? 

Yes. I have no plans to do that, though.

> PugSetup has been our go-to and it has quite literally EVERY feature we need other than kicking on match end.

Was just an idea, use whatever seems easiest.
