### ISSUE TITLE
Players/bots laying in the ground

### ISSUE THREAD

**Issue by suicidebro** [splewis/csgo-pug-setup#126]
During the knife round only players are literally floating/laying in the ground at certain times. Sometimes there standing but most of the time there floating in the ground. When the game starts this doesn't happen at all. During pregame it happens to the bots.

Is there some sort of fix for this?

**Comment by HalfEatenPie** [comment]
I would suggest this is an issue related with your installation of the game as the plugin doesn't touch any of that and simply sets the cvars up.  I'd verify your installation of CSGO or something. This is 100% not related to this plugin.

**Comment by splewis** [comment]
What @HalfEatenPie said.

If you have another plugin affecting players' knifes or models that's likely the root cause.
