### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by nitea2t** [splewis/csgo-pug-setup#128]
pugsetup.smx missing from build. Had to pull from Alliedmodders

**Comment by splewis** [comment]
Missing from what build? I don't see it missing from releases or the continuous builds.

**Comment by nitea2t** [comment]
https://github.com/splewis/csgo-pug-setup --> download zip

**Comment by splewis** [comment]
That would download the repository, which doesn't include it. Download an actual build.

https://github.com/splewis/csgo-pug-setup#download

**Comment by nitea2t** [comment]
Will do thanks for the help.
