### ISSUE TITLE
Gamestate

### ISSUE THREAD

**Issue by ixayldz** [splewis/csgo-pug-setup#129]
L 02/15/2016 - 09:00:47: SourceMod error session started
L 02/15/2016 - 09:00:47: Info (map "de_dust2") (file "errors_20160215.log")
L 02/15/2016 - 09:00:47: [SM] Unable to load plugin "pugsetup_teamlocker.smx": Native "GetGameState" was not found

**Comment by splewis** [comment]
You updated the pugsetup plugin but not the pugsetup_teamlocker plugin. Update them all.

**Comment by ixayldz** [comment]
i understand thanks its work now.
