### ISSUE TITLE
teamsize set 1

### ISSUE THREAD

**Issue by ixayldz** [splewis/csgo-pug-setup#130]
i set teamsize 1 for test  2 player.  after we type .ready  map vote is startting. but example we test on dust2. if we choose dust2 or random match is not starting but if we choose another map example inferno than map changing to inferno  and match start. whats is the problem ?

**Comment by ixayldz** [comment]
L 02/15/2016 - 12:10:03: Error log file session closed.
L 02/15/2016 - 12:15:06: SourceMod error session started
L 02/15/2016 - 12:15:06: Info (map "de_dust2") (file "errors_20160215.log")
L 02/15/2016 - 12:15:06: [SM] Plugin encountered error 4: Invalid parameter or parameter type
L 02/15/2016 - 12:15:06: [SM] Native "FormatNativeString" reported: Language phrase "ChangeMapMessage" not found
L 02/15/2016 - 12:15:06: [SM] Displaying call stack trace for plugin "pugsetup.smx":
L 02/15/2016 - 12:15:06: [SM]   [0]  Line 328, ./scripting/pugsetup/natives.sp::Native_MessageToAll()
L 02/15/2016 - 12:15:06: [SM] Plugin encountered error 4: Invalid parameter or parameter type
L 02/15/2016 - 12:15:06: [SM] Native "PugSetup_MessageToAll" reported: Error encountered while processing a dynamic native
L 02/15/2016 - 12:15:06: [SM] Displaying call stack trace for plugin "pugsetup.smx":
L 02/15/2016 - 12:15:06: [SM]   [0]  Line 10, ./scripting/pugsetup/maps.sp::ChangeMap()
L 02/15/2016 - 12:15:06: [SM]   [1]  Line 72, ./scripting/pugsetup/mapvote.sp::MapVoteHandler()

**Comment by ixayldz** [comment]
its okey you close this i fix everything its working fine your pugsetup now myfriend.

But i have 1 question is it possible change Random word in map vote ? when its display on screen  when player voting map.  can i change to random word to turkish word ?

**Comment by splewis** [comment]
That's what the translations system is for.

https://wiki.alliedmods.net/Translations_(SourceMod_Scripting)

https://github.com/splewis/csgo-pug-setup/tree/master/translations
