### ISSUE TITLE
live.cfg

### ISSUE THREAD

**Issue by immahobo** [splewis/csgo-pug-setup#132]
Instead of loading live.cfg first, I was wondering if it was possible to load live.cfg after knife.cfg if kniferound is enabled.

**Comment by HalfEatenPie** [comment]
If I recall if you have kniferound enabled then knife.cfg will automatically execute before the live.cfg is executed.  

Or were you looking for another way to execute the knife.cfg?

**Comment by splewis** [comment]
The live config is executed, then the knife config is executed. After that, the cvars changed by the knife config are restored to the values before the knife config was executed. I don't plan to change it.

**Comment by immahobo** [comment]
I am using log on in live.cfg and log off in knife.cfg, but after knife round the value does not revert.  Any ideas how I can get it to log on after knife?

**Comment by splewis** [comment]
"log" isn't a cvar, it's a command, so it can't be reverted. I'd either stop turning logging off or change it back on in one of the plugin's forwards, e.g. [PugSetup_OnLive](https://github.com/splewis/csgo-pug-setup/blob/master/scripting/include/pugsetup.inc#L99)

**Comment by immahobo** [comment]
I turn it logging off during knife because I only want to track stats during live on HLX.  I'm new to scripting, so I'm not sure how I would change it back in the code.

**Comment by splewis** [comment]
I'd probably do something like
```
#include <pugsetup>

public void PugSetup_OnWarmupCfgExecuted() {
	ServerCommand("log off");
}

public void PugSetup_OnLive() {
	ServerCommand("log on");
}
```
