### ISSUE TITLE
Enhancements/Bugs

### ISSUE THREAD

**Issue by zomgasd** [splewis/csgo-pug-setup#134]
1. Once the capacity reaches over 10 players and the remaining people are in spectators the ready/setup system gets bugged and it won't start the process for captains. 

Request: The people who have typed ".ready" are the only ones on the picking list.

2.Stats collection, I looked at the code for saving stats. I was wondering if there could be a better way to save the files preferably in a MYSQL database. The most consistent and easiest way that I believe to possibly balance the teams is by HLTV rating. 

Examples of how to calculate: http://i.imgur.com/EzkjFK9.png?1 + https://docs.google.com/spreadsheets/d/1jXTcTH6yoC9qClROazttHo2R3UYP7TNTETa6XIPCfh0/edit#gid=0

3.Instead of having to do .swap/.stay, I think maybe just having it exactly like ESEA's team choosing through chat by saying what team they want to be, just by saying "ct"/"t" in chat without quotes, and the losing team of the knife round to be irrelevant in the process!

**Comment by splewis** [comment]
1. I've never heard of that being an issue, but there is a cvar that changes if spectators are required to ready up or not.

2. I'm not going to add anything here. Feel free to make a pull request.

3. .t and .ct work as commands, don't want to add other commands for it

**Comment by zomgasd** [comment]
I have it set to exclude spectators from being ready, the GUI from where it says the captains Captains and amount of people ready glitches out when it happens

**Comment by splewis** [comment]
You're going to have to be more specific than "glitches out" in order to get it fixed.

**Comment by andersodt** [comment]
I've been manually messing around with autobalancing and stuff and have devised a couple different systems -- an ADR based RWS, HLTV Rating, and TrueSkill (like ELO and Glicko, but for teams -- trueskill.org). It's all just thrown on top of the regular RWS autobalancer and it's pretty messy code but it works for us. I don't plan on cleaning it up or anything at the moment but feel free to take a look at my fork and the TrueSkill branch if you want to build it yourself. It records all of the systems, but only balances based on TrueSkill.

**Comment by zomgasd** [comment]
@andersodt , does it use a MySQL database, if so, can it be used for a website to display stats? It looks great!

**Comment by andersodt** [comment]
It does not. However, I have had success symlinking the SQLite database to the web directory for the purposes of displaying the stats in a simple php page.

**Comment by zomgasd** [comment]
@andersodt I looked at your simple php page, I think it's the one on your GitHub if I'm not mistaken. Is it only if the SQLite is being hosted on the same server? Or can I possibly link that database to my server? Also, I'm running your stats plugin, I have it enabled, however, when I type .rws <name> it's not showing my stats.

**Comment by andersodt** [comment]
@zomgasd yeah, it was on the same server -- it was just the easiest/quickest solution we came up with.

What version of the pug-mod are you running? I've only tested it with 1.4.3.

**Comment by zomgasd** [comment]
@andersodt I'm using the current version 2.0.0, I was very interested once I saw your comment since I run 10 mans and stat collecting would be pretty nice, if I can just drag and drop where and how can I link the SQ3 database?

**Comment by splewis** [comment]
I'm not planning on adding more comprehensive stats systems to this plugin itself. Ideally someone creates stats collecting plugins that are independent of whether they are using pugsetup, warmod, eBot, or whatever.
