### ISSUE TITLE
Missing plugins?

### ISSUE THREAD

**Issue by Twistedwheelbarrow** [splewis/csgo-pug-setup#136]
Hey man,

How are the damage and money plugins enabled now? There is no longer a disabled folder containing them so I was essentially wondering how they are enabled/disabled.

Thank you in advance!

**Comment by splewis** [comment]
The last release and the continuous builds still have the plugins in the disabled directory as always.

**Comment by Twistedwheelbarrow** [comment]
I'm retarded today, don't worry. Thank you for reminding me though and for the fast response.
