### ISSUE TITLE
Knife Round

### ISSUE THREAD

**Issue by zomgasd** [splewis/csgo-pug-setup#137]
Disabling Friendly Fire and the command "kill" through console would be great additions.

**Comment by HalfEatenPie** [comment]
Friendly fire would be a simple config change in the knife.cfg config file if I recall. Should be in cfg/sourcemod/pugsetup/knife.cfg

Don't know about how to disable "kill" command in the console.

**Comment by zomgasd** [comment]
@HalfEatenPie Thank you for the FF one, I totally forgot. How about the "kill" command to disable it?

**Comment by HalfEatenPie** [comment]
Honestly man, I don't recall/know how to disable the kill command in the console, of course I never had a problem with that so I never needed to disable it.  I also haven't really looked into it so I hope someone else can chime in on that part.

**Comment by zomgasd** [comment]
@splewis is there anyway you can make captains do a 1v1 knife for a first pick that would be a nice small feature.

**Comment by splewis** [comment]
Don't want to add "kill" command blocking here, can be done through another plugin easily.

Also don't plan to add any 1v1 knife fighting.
