### ISSUE TITLE
Captain bug?

### ISSUE THREAD

**Issue by SpiritBob** [splewis/csgo-pug-setup#138]
Ok, here is exactly what happened.
.setup options were: Captains picked members, team size was 5, map selection is veto.
After everyone wrote .ready, captains started vetoing. The chosen map was de_cbble
Server successfully changed to said map, everoyne joined in, but captain seats were empty.
.setup settings were again the same as they are forced as default.
Previously captains were selected by an admin, who left the server.
Why weren't the previous captains in their spots?
Someone else became a captain, (don't know how, I think someone wrote !rand after seeing there were no captains) and after that, everyone wrote .ready,
captains remained in T/CT  (rest players were thrown in spec) and started choosing players, BUT after choosing them, they had to VETO AGAIN, forming a loop...
What went wrong!?? Why were there no captains, did !rand screw the process entirely and that's why we had to veto again? What would have happened if game started without assigned captains - would the previously assigned captains take their place? Thanks.
I'm using latest dev release.

EDIT: Off-topic question: How does RWS balancer work? After say we play 3 games with the same members, the plugin would have recorded some statistics for them and would auto balance teams - is that what it does? Thanks :)

**Comment by splewis** [comment]
I'm not aware of any bug like this. Can you reproduce it? (perhaps with 2 players)

Yes, that is what the autobalancer does.

**Comment by SpiritBob** [comment]
It hasn't happend in a while now. But captains still get auto placed and are not the same after map change. Try looking into that? It's fine tho, we always have an admin in the game that fixes the captain issue by appointing the correct captains, but still it shouldn't do that.
