### ISSUE TITLE
Add team names to demo naming scheme.

### ISSUE THREAD

**Issue by oalaro** [splewis/csgo-pug-setup#140]
> sm_pugsetup_demo_name_format (default "pug_{MAP}_{TIME}") - Naming scheme for demos. You may use {MAP}, {TIME}, and {TEAMSIZE}. Make sure there are no spaces or colons in this.

When everybody in the team uses the same tag, CS:GO automatically uses that as a team name. Is it possible to add {TEAMNAMES} or something like that. Also considering that there is a way to set team names with pugsetup_teamnames . Also for pugsetup_teamnames would it work like this?
`sm_name <STEAMID> <teamname> <teamflag>`

**Comment by splewis** [comment]
Sorry, I don't think is worthwhile doing in a pug-plugin.

**Comment by 1stator** [comment]
Given that this is one of the most used plugins for scrims now, would you still not consider it worthwhile?
