### ISSUE TITLE
Config based on Team Size

### ISSUE THREAD

**Issue by thakilla** [splewis/csgo-pug-setup#141]
Hey Guys,

First of all, thanks for that awesome plugin!
I would love to have different live configs depending on the configured team size.

1 = live1on1.cfg
2 = live2on2.cfg
3 = live3on3.cfg
4 = live4on4.cfg
5 = live5on5.cfg

Maybe not as an default, but maybe if there is a file which is named like that in the cfg folder. If not, take live.cfg as always.

**Comment by BarclayTech** [comment]
You can assign custom configs via the pugsetup.cfg

I remember him working on a config selector but I don't think Splewis finished it.

ESL provide 1on1,2on2,3on3 and 5on5 configs, so just download the ones you need.

**Comment by splewis** [comment]
I don't think I want this added into pugsetup itself, but you could use the pugsetup forwards/natives to accomplish this.

Something like:
```
public void PugSetup_OnReadyToStart() {
	TeamType teamType;
	MapType mapType;
	int playersPerTeam;
	bool recordDemo; 
	bool knifeRound; 
	bool autoLive;
	PugSetup_GetSetupOptions(teamType, mapType, playersPerTeam, recordDemo, knifeRound, autoLive);

    ConVar configCvar = FindConVar("sm_pugsetup_live_cfg");
    char newConfig[PLATFORM_MAX_PATH];
    Format(newConfig, sizeof(newConfig), "live%don%d.cfg", playersPerTeam, playersPerTeam);
    configCvar.SetString(newConfig);
}

**Comment by thakilla** [comment]
Thanks! I will try this.

**Comment by thakilla** [comment]
Works like a charm.
I created a little plugin which uses your "events" and added some text phrases to the chat.

Thanks!
