### ISSUE TITLE
Pug Order

### ISSUE THREAD

**Issue by AngelGuard** [splewis/csgo-pug-setup#142]
Hey - why have you changed the order so map vote is first then captains? 

Also I tried the .rand feature but it didn't seem to work, did I do it too early?

**Comment by splewis** [comment]
I haven't changed anything about the order. There's an open issue to change it, though: https://github.com/splewis/csgo-pug-setup/issues/92

When did you use .rand?

**Comment by AngelGuard** [comment]
when i first received this i used to do this..
.setup go through those settings, then .rand and it would assign cap's there and then. .

Regarding the order. Okay. Perhaps I've forgotten as its been many months

**Comment by SirBarclay** [comment]
Don't know what the exact problem is.

I went into the setup. Selected captains, map vote, etc.

Then in the .ready stage I did .rand, followed by readying up.

Popped up saying I was team captain, then once everyone was ready the map voting stage began.

Is that the desired outcome or am I getting it backwards?

**Comment by splewis** [comment]
Closing since it's a duplicate of https://github.com/splewis/csgo-pug-setup/issues/92
