### ISSUE TITLE
missing pugsetpup.smx and disabled folder

### ISSUE THREAD

**Issue by xestho** [splewis/csgo-pug-setup#143]
Hey there

I've tried to install the pug-setup but there is no pugsetup.smx file any more on the 2.0 release. Do I get something wrong from the readme or is the file missing?

Thank you for your help

**Comment by splewis** [comment]
Looks fine to me.

```
splewis-laptop Downloads $ wget https://github.com/splewis/csgo-pug-setup/releases/download/2.0.0/pugsetup_2.0.0.zip

Saving to: ‘pugsetup_2.0.0.zip’

100%[================================================>] 304,988      935KB/s   in 0.3s   l

2016-05-03 15:22:09 (935 KB/s) - ‘pugsetup_2.0.0.zip’ saved [304988/304988]

splewis-laptop Downloads $ ls
pugsetup_2.0.0.zip
splewis-laptop Downloads $ unzip -q pugsetup_2.0.0.zip 
splewis-laptop Downloads $ ls addons/sourcemod/plugins/
disabled  pugsetup.smx
```


You probably downloaded the source code instead of the release. https://github.com/splewis/csgo-pug-setup/releases/tag/2.0.0

**Comment by xestho** [comment]
You are right, downloaded multiple times the source.

Appreciate your work and thanks for your help

**Comment by SirBarclay** [comment]
Quick pointer, if you want "unstable" releases then Splewis has Jenkins setup @ http://ci.splewis.net/
