### ISSUE TITLE
What convars the ".setup" use to configure the match ?

### ISSUE THREAD

**Issue by TheAcastus** [splewis/csgo-pug-setup#144]
I am wondering about setting up the match using external app. Like website, which will be connected to the server using rcon or sending commands to the screen. 

I am able to use, one of those two ways to manage the server. But I dont know the names of convars. If the plugin use some.
Basicaly I need all of them in ".setup". I mean
 - map
 - map vote
 - captains
 - player team choosing
 - players per team
 - demo
 - knife round
 - auto map change to the match map, if it was choosen before (could be used sm_map)
 - warmup (aim/not aim)
etc...

Why I am asking and not looking into README.md - because i didnt what im looking for.
We are usualy custumizing the matche while im playing with friends etc... 
Yes. i could have one 1v1 setup config to execute. But that is not thing which i want.

**Comment by splewis** [comment]
There aren't cvars, they're saved in a [config](https://github.com/splewis/csgo-pug-setup/blob/master/configs/pugsetup/setupoptions.cfg) file so that they can be modified by admins on the server.

**Comment by TheAcastus** [comment]
Ok, is there any option to setup the match without joining the game? Or i need to do it everytime ?

**Comment by splewis** [comment]
There is a ``sm_pugsetup_autosetup`` cvar

**Comment by TheAcastus** [comment]
Ok, and is there way to custumize the setup withou using many configs ?

**Comment by TheAcastus** [comment]
I think that I find out how could I do it. It would be a lot of .cfg files and much more work than I think. But I think that I can do it as I want on my own.

#144 Closed.
