### ISSUE TITLE
Captains is not automatically picked at random

### ISSUE THREAD

**Issue by penetal** [splewis/csgo-pug-setup#148]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:
### Expected behavior

Captains should be automatically selected, one from each team.
### Actual behavior

Still have to type `.capt` or `.rand`
### Steps to reproduce
- Plugin version:
  2.0.1
- Sourcemod version:
  v1.8.0.5915

I have it enabled, and checked via sm_cvar to make sure it was set as it should.

```
cfg/sourcemod/pugsetup/pugsetup.cfg:sm_pugsetup_auto_randomize_captains "1"
cfg/sourcemod/pugsetup/pugsetup.cfg:sm_pugsetup_snake_captain_picks "0"
```

**Comment by splewis** [comment]
I can't really do a test, but this should work. How many players are in the server when you're doing this test? The feature only takes effect when enough players join the server (see https://github.com/splewis/csgo-pug-setup/blob/master/scripting/pugsetup.sp#L522)

**Comment by splewis** [comment]
I believe this is fixed now. The next release should contain the fix.
