### ISSUE TITLE
Demo recording stops at round 25

### ISSUE THREAD

**Issue by DUSTY007** [splewis/csgo-pug-setup#149]
Hello,

the demo record stops at round 25 so the last rounds are missing.

### Steps to reproduce
- Plugin version:  "CS:GO PugSetup" (2.0.0) by splewis
- Sourcemod version:   SourceMod Version: 1.8.0.5942

**Comment by splewis** [comment]
It's highly unlikely there is a plugin bug here. Can you reproduce this? Were and tv_* commands executed on the server?

**Comment by DUSTY007** [comment]
Hey,

yes gotv is completly enabled on the server. Does a demo stop when a game is paued for example ?

**Comment by splewis** [comment]
my question was whether commands were being executed during the game, either by a human or by another plugin.

No, it stops when the win panel shows up (the "cs_win_panel_match" event). The logic is very simple and has been unchanged for 2+ years, so I find it unlikely there's a bug here. Have you tried to reproduce this?

**Comment by splewis** [comment]
Closing since there's been no response and I don't believe there's a reproducible bug here.
