### ISSUE TITLE
SteamWorks error in Linux Server

### ISSUE THREAD

**Issue by mariodaelizabeth** [splewis/csgo-pug-setup#150]
Hello, splewis
I really happy to use csgo-pug-setup :D without you, i can't play competitive match in community server hehe

I have a problem, mate. When i try to compile pugsetup.sp "./compile.sh pugsetup.sp", my terminal send me error information such as pugsetup.sp(11) : fatal error 183: cannot read from file: "SteamWorks"

Do you know how to fix it, mate ?

### Steps to reproduce
- Plugin version: 2.0.1
- Sourcemod version: 1.8 - build 5946

**Comment by splewis** [comment]
You need the steamworks include file to compile it: https://forums.alliedmods.net/showthread.php?t=229556

**Comment by mariodaelizabeth** [comment]
Thank you for your time to solve my problems, mate.
Could you tell me what are differences between SteamWorks.ext.dll and SteamWorks.inc ?
Which one should i use ?

**Comment by splewis** [comment]
The .inc file is the include file needed for compiling.

The .dll file is the extension binary compiled for windows.
