### ISSUE TITLE
PugSetup Compile Error

### ISSUE THREAD

**Issue by armansalehzadeh** [splewis/csgo-pug-setup#153]
Hello EveryOne
I Want To Compile PugSetup Plugin But I have this error .
PugSetup.sp
Pugsetup.sp<11> : Fatal error 183 : cannot read from file: "SteamWorks"
Compliation Aborted.
1 Error.

- Plugin version: 2.0.1
- Sourcemod version:1.8.0
![pug](https://cloud.githubusercontent.com/assets/23198182/19903386/c1e7dcea-a083-11e6-9988-b36555f50fd5.PNG)

**Comment by splewis** [comment]
You need the Steamworks include to compile: https://github.com/KyleSanderson/SteamWorks/blob/master/Pawn/includes/SteamWorks.inc
