### ISSUE TITLE
[Issue] After ending current PUG Setup , Vote Next Map is not working

### ISSUE THREAD

**Issue by TandelK** [splewis/csgo-pug-setup#154]
After the round of PUG is completed it just auto loads the same map and does not show Next Map option. I did mention my gamemode_competitive_server.cfg file in pugsetup.cfg area after completing match section. 

I also added mp_endmatch_votenextmap 1 to my live.cfg file . Still it does not show any Maps sections after the match is over.

**Comment by splewis** [comment]
pugsetup doesn't interfere with any map voting logic at the end of a map. That's up to whatever other plugins you have, and whatever cvars you have in your live config. 

If you believe there's a pugsetup bug, feel free to reopen.
