### ISSUE TITLE
Give players time to reconnect instead of immediately freeing it up?

### ISSUE THREAD

**Issue by Walks2000** [splewis/csgo-pug-setup#156]
Currently using this plugin for CS:CO and has been working perfectly fine so far, however an issue that is happening is while the map changes or people's games crash for example they lose their slot with no chance of reconnecting in time. I was wondering if there is a way to give people like 3-5 minutes before making their slot public?

**Comment by splewis** [comment]
There's no way to do this right now. You'd have to write another plugin using the pugsetup api to reserve slots.

**Comment by Walks2000** [comment]
Ahhh thanks for that splewis, bit annoying when people lose their slots but if there is nothing to do then I don't really have a choice, thanks for all the great plugins you've made though splewis, community would have less servers/modes if you didn't bring out new ones.
