### ISSUE TITLE
Random Teams

### ISSUE THREAD

**Issue by spot88** [splewis/csgo-pug-setup#157]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior
Totaly Random scramble

### Actual behavior
Don't seems like it, sometimes only changes 1 person. 

### Steps to reproduce
- Plugin version: "CS:GO PugSetup" (2.0.1+409) by splewis
- Sourcemod version:1.8.0.5964

**Comment by splewis** [comment]
Unless it *always* only changes 1 player, I don't think there is a bug here. Random means random, sometimes 0 players might switch teams.

**Comment by spot88** [comment]
Okay, might be.

**Comment by spot88** [comment]
Where can i find the code that randomize?

**Comment by splewis** [comment]
https://github.com/splewis/csgo-pug-setup/blob/master/scripting/pugsetup.sp#L1618

**Comment by spot88** [comment]
It seems there may be a possibility for a player to be placed on teams two times as the algoritm runs. Will this affect scrambling of the other players?

## http://pastebin.com/xny7RkYD ##
Placed 1  on T
Placed 2  on CT
Placed 3  on T
Placed 4  on CT
Placed 5  on CT
Placed 6  on CT
Placed 7  on CT
Placed 7  on T
Placed 8  on T
Placed 9  on T

Players T: 5
Players CT: 5
Process finished with exit code 0

**Comment by spot88** [comment]
@splewis

**Comment by splewis** [comment]
Your python code is different from the plugin. Else if (elif in python) are needed so that doesn't happen.

**Comment by spot88** [comment]
Valid point! Then i guess your method is good enough for scrambling teams :p 
sorry i doubted your skills :D
