### ISSUE TITLE
Overtime instead of draw

### ISSUE THREAD

**Issue by MySelfLuls** [splewis/csgo-pug-setup#158]
Hello,
I hosted a tournament recently, one of the rounds ended in a draw, I was considering if it is possible to enable overtime, just like they use in Faceit, ESL etc.
If this is a feature already, please do tell as I have yet to have found it.

**Comment by splewis** [comment]
You just set ``mp_overtime_enable 1``. It's set in the [default config](https://github.com/splewis/csgo-pug-setup/blob/master/cfg/sourcemod/pugsetup/live.cfg#L20).
