### ISSUE TITLE
Possible bug maxteamsize

### ISSUE THREAD

**Issue by ngx3** [splewis/csgo-pug-setup#159]
So I installed pugsetup on one of my servers and it appears that maxteamsize does not work, because we were in a 5v5 match, 12 slot server for spectators and one person was able to join the match. During .setup team max size was 5.

### Steps to reproduce
- Plugin version: pugsetup 2.0.1
- Sourcemod version: 1.8.0-git5969

**Comment by splewis** [comment]
As I remember, that's because pugsetup doesn't actually lock teams by default. The max team size in the pugsetup plugin is primarily for knowing when to start the game.

If you want to prevent extra players from joining a full/live game you'd have to enable the [pugsetup_teamlocker](https://github.com/splewis/csgo-pug-setup#pugsetup_teamlocker) addon plugin.

**Comment by ngx3** [comment]
> As I remember, that's because pugsetup doesn't actually lock teams by default. The max team size in the pugsetup plugin is primarily for knowing when to start the game.

Makes sense, thing was I saw someone using a similar setup with 12 slots, 2 for spectators and had https://forums.alliedmods.net/showpost.php?p=2328112&postcount=9 to set teams 5v5 and 2 spec since mp_spectators_max 2 doesnt work.




 Where do I download these addon plugins?? Because I'd also like pugsetup_autokicker.cfg, when two captains are selected players get moved to spectator, but are allowed to join teams without captains picking them.

**Comment by splewis** [comment]
https://github.com/splewis/csgo-pug-setup#installation

They're in the regular release download, but in the ``addons/sourcemod/plugins/disabled`` directory. You move them up to the ``plugins`` directory to enable them.

**Comment by ngx3** [comment]
Ok, thanks.

One question when we initiated "Load practice mode" and then proceeded to start a match, showimpacts, noclip and 16000k cash was still loaded after the match was live.

**Comment by splewis** [comment]
If there's a bug with the practicemode/pugsetup interaction you should file a separate  bug with the version info of both. I'll close this since there's no bug with the team sizes as far I as I know.
