### ISSUE TITLE
!unban or sm_unban

### ISSUE THREAD

**Issue by mariodaelizabeth** [splewis/csgo-pug-setup#161]
Hello,
I banned a cheater from my community servers using sm_ban "XXX" "0" "Hax" command
And i wanted to unban XXX using sm_unban "XXX" but XXX can't join my server.
Do csgo-pug-setup have a special unban command ?

**Comment by splewis** [comment]
Nope. pugsetup doesn't do anything with bans. Sourcemod and CS:GO have their own banning mechanisms, but I'm not very familiar with them. 

I would suggest checking if there are files called banned_user.cfg and banned_ip.cfg.

**Comment by splewis** [comment]
Closing since this isn't related to pugsetup.
