### ISSUE TITLE
Practice mode still enabled when match is live

### ISSUE THREAD

**Issue by ngx3** [splewis/csgo-pug-setup#162]
We were playing practice for about one to two hours and when are friends were coming to play a match we disabled practice mode by hitting "load practice mode" which confirms the plugin being disabled in chat. We started the match setup and before everyone could ready up showimpacts and noclip etc.. were enabled still so we thought it would disappear when the match was live, but it wasn't..

### Actual behavior
when we initiated "Load practice mode" and then proceeded to start a match, showimpacts, noclip and 16000k cash was still loaded after the match was live.

### Steps to reproduce
- Plugin version: PUG: 2.0.1 and Practice mode: 1.0.0
- Sourcemod version: 1.8 5969

**Comment by splewis** [comment]
> disabled practice mode by hitting "load practice mode"

Is that a typo? Load practice mode would **enable** it.

**Comment by ngx3** [comment]
There is no other option to disable it. But its pretty straight forward you click it for the first time and it enables, hit it again and it disables. It even confirms it in chat "Practice mode, disabled".

**Comment by splewis** [comment]
Typically the "start practice mode" menu button changes to one that says "exit practice mode". 

Can you reproduce any issues with only practicemode, without pugsetup? It sounds like this is unrelated to pugsetup.

**Comment by ngx3** [comment]
''disabled practice mode by hitting "load practice mode"
Sorry that was when I only had practice mode enabled

**Comment by splewis** [comment]
> When I had just practice mode it was a little bit buggy, for example, only sometimes showimpacts would work etc..

I haven't managed reproduce any issues, so unless you give clear steps there's not much I can do.

**Comment by splewis** [comment]
Never got any way to reproduce this. Closing.
