### ISSUE TITLE
When a team loses rounds the money doesnt reset to what its suppose to be after half time and sometimes before.

### ISSUE THREAD

**Issue by crooksst** [splewis/csgo-pug-setup#163]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior
Round Loss Bonus

### Actual behavior
When a team loses rounds the money doesnt reset to what its suppose to be
usually in csgo if a team loses 5 rounds in a row the teams players get a bonus of 3400$
if they win a round in these situations this is the money theyre suppose to get.
CS:GO Economy

Objective	Team Reward	Player Reward
Kill all enemies	3250	
Timer runs out (CT)	3250	
Defuse bomb	3500	300
Bomb explodes	3500	
Bomb plant		300
Lose 1st round	1400	
Lose 2 in a row	1900	
Lose 3 in a row	2400	
Lose 4 in a row	2900	
Lose 5 in a row	3400	
Lose, but get bomb plant (T)	800
but the money bonus or reset isnt acting like this unless i disable pug setup.

also at half time the money doesnt reset for a team if they have lost 5 rounds or more and lose 1st round after half time. which means they lose a pistol round and dont get a bomb plant and have AK's and armor and some nades....

### Steps to reproduce
- Plugin version:  "CS:GO PugSetup" (2.0.1) by splewis
- Sourcemod version: SourceMod (1.8.0.5964) by AlliedModders LLC

**Comment by splewis** [comment]
pugsetup doesn't affect the money system. What it does do is exec configs of your choosing, which might affect the cash_* cvars. That's more likely what is happening. 

My guess is that you're launching the server as casual (making gamemode_casual.cfg the default config) and didn't copy the live/warmup configs provided by default in ``cfg/sourcemod/pugsetup``. (see https://github.com/splewis/csgo-pug-setup/tree/master/cfg/sourcemod/pugsetup)

Are there files in cfg/sourcemod/pugsetup, or did you change the live/warmup config cvars?

**Comment by crooksst** [comment]
didn't change anything in cfg/sourcemode/pugsetup but it can be what u said about the server being launched in gamemode casual. let me make sure its in competitive in the launch parameters on firedaemon first and also working with default configs. i'll redownload the live/warmup configs and overwrite the ones in there if it doesnt work and post my results. Thank you splewis i'll keep you posted

**Comment by splewis** [comment]
Closing since there's no update and I believe this is a user config issue.
