### ISSUE TITLE
Different configs? Disabled Plugins?

### ISSUE THREAD

**Issue by webdesign3r** [splewis/csgo-pug-setup#167]
Hi,
is it possible to load different configs for 5on5, 1on1 etc? or is it always the "live.cfg"?
also, how can I enable the disabled plugins? I know i read it somewhere, but i am to blind to find it again.. practice mode for example doesnt appear in the menu for me, but I can load it with sm_prac in console

**Comment by splewis** [comment]
1. You can change the ``sm_pugsetup_live_cfg`` cvar.

2. They're in ``addons/sourcemod/plugins/disabled``, move them up 1 directory (https://github.com/splewis/csgo-pug-setup#installation)

3. It normally appears on the .setup menu, usually as the last item. It does at the current 2.0.2 release for me.
