### ISSUE TITLE
Team switching after match is live?

### ISSUE THREAD

**Issue by cre0n** [splewis/csgo-pug-setup#168]
### Expected behavior
After going live, and someone disconnects from the server, people from the enemy team shouldnt be able to switch the team and take his place

### Actual behavior
Switching is possible after someone leaves

Is there a convar against that I just didn't find yet? :S

**Comment by splewis** [comment]
pugsetup doesn't do that by default (or have a cvar, though it probably should).

You can enable the [pugsetup_teamlocker](https://github.com/splewis/csgo-pug-setup#pugsetup_teamlocker) plugin and it will block team switches, though.

**Comment by cre0n** [comment]
Thanks for the fast reply!
I thought I had the teamlocker plugin enabled already, but I may have forgot to restart the server. I'll try again later on today and give you an update!

**Comment by cre0n** [comment]
Sooo, apparently even with the enabled teamlocker plugin, you're able to switch the team as soon as the match is live and someone from the enemy team disconnects. :/

sm_pugsetup_block_spectate_joins "1"
sm_pugsetup_kick_time "0"
sm_pugsetup_teamlocker_enabled "1"

**Comment by splewis** [comment]
The teamlocker is just supposed to block joins to full teams, not be a strict team locking mechanism (https://github.com/splewis/csgo-pug-setup/blob/master/scripting/pugsetup_teamlocker.sp#L17)

All of pugsetup is generally intended for private servers where players are trusted, and would require other plugins to work in a more public sense. get5 locks players to teams by steamids.

**Comment by crashzk** [comment]
I believe that now we can think about it again, it really is very useful to have some option to block the team change when the game is live.
