### ISSUE TITLE
C4 and round timers incorect

### ISSUE THREAD

**Issue by mattnotley** [splewis/csgo-pug-setup#169]
We have a csgo server which we customize via clanforge.
We start up a server with the pug mod addon installed and mp_roundtime_defuse 1.92 mp_roundtime 1.92 mp_c4timer 40 are all correct. when we all ready up and the pug does the restarts the round timer changes to to 1:45 and c4 timer to 35 seconds. Ive checked and the live.cfg config is correct round timer and c4 timer are correct. Also when it switches to the knife round there is no armour despite it being mp_free_armour 1

Is this a known issue if so how do you fix it?

im running plug in version 2.0.1

**Comment by splewis** [comment]
It's not a known issue, and probably the result of a installation issue.

I would check the value of ``sm_pugsetup_live_cfg`` to see what the actual live config is, then check that file. I don't know anything about clanforge, but they are probably doing something weird with your installation that involves outdated configs.

**Comment by mattnotley** [comment]
sm_pugsetup_live_cfg "sourcemod/configs/pugsetup/live.cfg"
That's is the what it says in pugsetup.cfg
The location of live.cfg matches up. 
We have had a few issues with configs so I'll contact clan forge. 
Thanks for your help

**Comment by splewis** [comment]
I'm closing since I don't see any indication this is a problem with pugsetup. You can reopen if you feel that's not the case.
