### ISSUE TITLE
Demo directory

### ISSUE THREAD

**Issue by leffeiilp** [splewis/csgo-pug-setup#172]
Hello splewis!

I wanna start of by saying that ive been using this mod for almost 2 years and i love it.
I wanted to ask if there is any way to save my demos in a diffrent folder?

best regards

**Comment by splewis** [comment]
You should be able to change the sm_pugsetup_demo_name_format cvar to something like:
``mydirectory/pug_{MAP}_{TIME}``

The default is ``pug_{MAP}_{TIME}``

**Comment by leffeiilp** [comment]
Thanks,

well i tried this and i changed to: Demos/DEMO_{MAP}_{TIME}

But now there is no demo saved after the match has ended

**Comment by leffeiilp** [comment]
Anyone else who could please help me?

**Comment by leffeiilp** [comment]
I can confirm that its not working fine!

thanks again!

post closed

**Comment by luckykev** [comment]
I think he meant that it is* working fine.

I used this change, created the directory, and it works.

**Comment by leffeiilp** [comment]
I can confirm that it is working fine.

thanks again!

post closed

**Comment by spacecow123** [comment]
@luckykev @leffeiilp can you help me out I created a demo directory in CSGOSL\csgosl\server\csgo\Demos and then changed the cvar to "Demos/pug_{MAP}_{TIME}". Is that new directory in the right place it does not seem like the demo recorded in the right place when I changed it.
