### ISSUE TITLE
Players frozen in spawns after match end

### ISSUE THREAD

**Issue by luckykev** [splewis/csgo-pug-setup#173]
### Expected behavior

At the end of a match there is a countdown. After the countdown, the round should restart and the game should go back into warmup mode (re spawn on death, free to move/shoot)

### Actual behavior

Sometimes (~20% of matches so far), after the end of match countdown, the round restarts but players are stuck in their spawns with constant immunity (they can't move and they're transparent/immune). The ready-up system still seems to function, though.

**EDIT: This has been happening a lot more often recently, up to like 75% of matches.**

<s>Fix so far has been to change the map.</s>
Setting mp_match_end_restart 0 does not fix. Still happens after some games.

### Steps to reproduce

Nothing noteworthy.

- Plugin version: latest
- Sourcemod version: latest

**Comment by luckykev** [comment]
Still seeing this issue over and over...

**Comment by luckykev** [comment]
Still seeing this issue over and over... @splewis @technoblazed

**Comment by Technoblazed** [comment]
Looking into a patch at the minute.

**Comment by splewis** [comment]
Without any reproduction steps there's not much I can do. I've never seen this in ~hundreds of games using this plugin with the default settings/configs provided. 

Are you running other plugins? Changing any cvars? I'd suspect anything warmup/freezetime related based on your description.

**Comment by luckykev** [comment]
@splewis At the time the issue began, no, I hadn't been running other plugins. @Technoblazed has seen this issue as well before. I will upload my configs (or Techno can, he has access) to my servers later to show

**Comment by luckykev** [comment]
@splewis Here's my pugsetup, live, warmup, knife cfg. I'll try to get a screenshot in-game next time it happens (doesn't happen after ever match - nothing obvious causing it when it does)

[knife.txt](https://github.com/splewis/csgo-pug-setup/files/905636/knife.txt)
[live.txt](https://github.com/splewis/csgo-pug-setup/files/905637/live.txt)
[pugsetup.txt](https://github.com/splewis/csgo-pug-setup/files/905635/pugsetup.txt)
[warmup.txt](https://github.com/splewis/csgo-pug-setup/files/905634/warmup.txt)

**Comment by luckykev** [comment]
@splewis @Technoblazed Looks like I had mp_match_restart_delay set to 15 and that may have been interfering with the timings of the plugin.

I returned mp_match_restart_delay to 30 like in the default live.cfg.

Will keep this thread updated...

**Comment by luckykev** [comment]
Was working fine for several games after extending the restart delays to default pugsetup, but just happened two games in a row where at the end of the game, in the middle of the winpanel timeleft countdown, it went into captain-picking-teams mode... hence the getting stuck in spawn with immunity

**Comment by luckykev** [comment]
Fixed by creating a separate postgame cfg with sm_forcestop in it

**Comment by NotRuben** [comment]
> Fixed by creating a separate postgame cfg with sm_forceend in it

how exactly did you add this into the server? and how did you tell it went to exacute the file?

**Comment by NotRuben** [comment]
under pugsetup.cfg  
sm_pugsetup_postgame_cfg

made a new cfg file
named it
forceend.cfg
in that file add
sm_forceend
edit pugsetup.cfg 

// Config to execute after games finish; should be in the csgo/cfg directory.
// -
// Default: "sourcemod/pugsetup/warmup.cfg"
sm_pugsetup_postgame_cfg "sourcemod/pugsetup/forceend.cfg"

**Comment by NotRuben** [comment]
> under pugsetup.cfg sm_pugsetup_postgame_cfg
> 
> made a new cfg file named it forceend.cfg in that file add sm_forceend edit pugsetup.cfg
> 
> // Config to execute after games finish; should be in the csgo/cfg directory. // - // Default: "sourcemod/pugsetup/warmup.cfg" sm_pugsetup_postgame_cfg "sourcemod/pugsetup/forceend.cfg"

Nvm this didn't fix for me
