### ISSUE TITLE
 leavers feature and autostop

### ISSUE THREAD

**Issue by filoret256** [splewis/csgo-pug-setup#177]
Hi

can you add leavers feature ?
if some player leave live match he is autoban after timeout

**sm_leave_timer** - default 3min like at official MM
**sm_leave__bancommand** - make this for different plugins support
**sm_leave_unlock_team** - for pugsetup_teamlocker team unlock

and another feature
**autostop** if where are < players at server

### Steps to reproduce
- Plugin version: dev 411
- Sourcemod version: 1.8.0.5981 - current stable

**Comment by splewis** [comment]
I'm not planning on adding any of these.

Someone is free to create a new plugin using the [api](https://github.com/splewis/csgo-pug-setup/blob/master/scripting/include/pugsetup.inc), but I don't plan on adding such a feature to pugsetup here.
