### ISSUE TITLE
Captains hint message becomes useless with long names

### ISSUE THREAD

**Issue by luckykev** [splewis/csgo-pug-setup#181]
### Expected behavior

Hint message, when displaying Captain 1 and 2, should be set to have a character limit per line so if Captain 1 has a long name, it doesn't continue into a 2nd line cutting off Captain 2's name.

### Actual behavior

See screenshot:
http://steamcommunity.com/sharedfiles/filedetails/?id=899254720

### Steps to reproduce
- Plugin version: Latest
- Sourcemod version: Latest

**Comment by Technoblazed** [comment]
Fixable, will push PR later.

**Comment by luckykev** [comment]
@Technoblazed u fix this yet tehe
