### ISSUE TITLE
[FEATURE] Ability to restrict previous 'x' maps from being chosen

### ISSUE THREAD

**Issue by Technoblazed** [splewis/csgo-pug-setup#182]
It would be pretty helpful to block maps that had just been played from being played again.

Giving a server the ability to block the last x amount of maps would allow for more diversity between maps on the server.

**Comment by splewis** [comment]
Sounds like a good idea to me.

The sourcemod mapchooser plugin has support for this, but I don't think it should be used. I think pugsetup should just internally store what maps pugs have been played - I think in-memory storage should be fine.

**Comment by Technoblazed** [comment]
Tried to give it a go today,  couldn't figure out where the best place to put the code in, everything seems to rely on something else, so much goes into the current voting system.

**Comment by splewis** [comment]
My suggestion would be: to edit [mapvote.sp](https://github.com/splewis/csgo-pug-setup/blob/master/scripting/pugsetup/mapvote.sp) and [instantrunoffvote.sp](https://github.com/splewis/csgo-pug-setup/blob/master/scripting/pugsetup/instantrunoffvote.sp) to not directly use the g_MapList global, but use a different ArrayList (g_MapVotePool or something) that is filled when the vote is created. So g_MapList is only used to construct this new list in ``CreateMapVote``, and not used elsewhere for voting.

There was a useless wrapper on g_MapList which made it less obvious what was happening, but I got rid of that (https://github.com/splewis/csgo-pug-setup/commit/649c9f35020991a06392ed9ed0da6d20b74e5ec6).

**Comment by Technoblazed** [comment]
Well, I had it working with the GetCurrentMapList() but just checked the commits here and it's been removed, time to start again ;-;
