### ISSUE TITLE
config and map list choosing feature not working

### ISSUE THREAD

**Issue by superbroleon** [splewis/csgo-pug-setup#187]
### Expected behavior
I got the liveconfig.cfg and maplist.cfg setup properly and should be able to choose a config and maplist in the setup. 

liveconfig.cfg:

```
"LiveConfigs"
{
	"Default5v5"		"sourcemod/pugsetup/live.cfg"
	"1o1"			"esl1on1.cfg"
	"1o1Knife"		"esl1on1knife.cfg"
	"1o1Awp	"		"esl1on1awp.cfg"
	"1o1Pistol"		"esl1on1pistol.cfg"	
}
```

maplist.cfg

```
"MapLists"
{
	"Standard"		"maps.txt"
	"test1"			"testmaps.txt"	
	"test2"			"testmaps2.txt"
}

```

### Actual behavior
But i can't choose anything. The menu point for it  just doesn't show up. Maybe i didnt even download evrything i need for that but its kinda confusing because it's like 2 years old.

### Steps to reproduce
- Plugin version: 2.0.2
- Sourcemod version: 1.9 - build 6083

**Comment by Technoblazed** [comment]
As far as I'm aware, there are no longer features of the plugin? Would you be able to link to where you got this information from?

**Comment by superbroleon** [comment]
Alright this is pretty likely true...i just clicked through the github tree:
 [https://github.com/splewis/csgo-pug-setup/tree/feature-config-choosing](url)

So thats probably why its not working anymore. Anyway do you know like a addon plugin for the pug setup which allows to choose your live config individually? Because i think that is like almost a must have feature, and i dont wanna get some else pug addon because this is really good and clean.

**Comment by Technoblazed** [comment]
I see! What you've got there is on a different tree, not the master branch, which means it's currently not implemented into the main plugin, this should probably be turned into a feature request instead of a bug report if a similar one does not already exist.

**Comment by superbroleon** [comment]
Ye, will do that. So just to be clear, you dont know some plugin like this?
