### ISSUE TITLE
PugSetup not working after 5/12/17 CSGO update

### ISSUE THREAD

**Issue by luckykev** [splewis/csgo-pug-setup#189]
# 5995 SM game data update fixes this!

@splewis 

### Expected behavior

.ready system works like normal

### Actual behavior

not functional, no .ready, says plugin is loaded though

Spams this in the logs over and over:

L 05/12/2017 - 17:50:50: [SM] Call stack trace:
L 05/12/2017 - 17:50:50: [SM]   [0] CS_GetClientClanTag
L 05/12/2017 - 17:50:50: [SM]   [1] Line 1860, ./scripting/pugsetup.sp::UpdateClanTag
L 05/12/2017 - 17:50:50: [SM]   [2] Line 460, ./scripting/pugsetup.sp::Timer_CheckReady
L 05/12/2017 - 17:50:50: [SM] Exception reported: Failed to locate function
L 05/12/2017 - 17:50:50: [SM] Blaming: pugsetup.smx

**Comment by Technoblazed** [comment]
Sourcemod issue. Wait for a patch or alternative.

**Comment by luckykev** [comment]
Updated to SM 5993, .ready system works, but PugSetup crashes the server when the match goes live (after knife round) which was not an issue pre-updates @splewis @Technoblazed

**Comment by luckykev** [comment]
Updated to SM 5993, same as above. From -condebug console.log right before crash:

`[PUG] LIVE!
[PUG] LIVE!
[PUG] LIVE!
[PUG] LIVE!
[PUG] LIVE!
lucKykev: LIVE
L 05/13/2017 - 09:10:32: "lucKykev<4><STEAM_1:0:203268460><CT>" say "LIVE"
L 05/13/2017 - 09:10:32: Starting Freeze period
L 05/13/2017 - 09:10:32: World triggered "Match_Start" on "de_mirage"
Failed to load gamerulescvars.txt, game rules cvars might not be reported to management tools.
Server is hibernating`

@splewis @Technoblazed

**Comment by luckykev** [comment]
CS_GetTeamScore function is to blame...

From @Technoblazed:
```
Just ran an accelerator test, looks like "CS_GetTeamScore" gamedata might not be correct, any chance you can give it a look?
