### ISSUE TITLE
[Suggestion/more question] Captain read from file, ready to play?

### ISSUE THREAD

**Issue by AdrianJaniczek** [splewis/csgo-pug-setup#190]
can i edit the plugin so that players dont have to write .setup, the game is already ready to go, and make a file to read from so that there are already set captains?

Thanks

**Comment by Technoblazed** [comment]
The first part can be done through game cvars, please read here: https://github.com/splewis/csgo-pug-setup/wiki/Frequently-Asked-Questions#is-this-plugin-usable-in-a-public-server

**Comment by AdrianJaniczek** [comment]
ah awsome cheers, do you know about the reading captains from files?

**Comment by Technoblazed** [comment]
People have asked for it, its not implemented yet.

**Comment by splewis** [comment]
I'm not going to add this to pugsetup since it's use case seems to narrow.

It can be implemented in another plugin via the [PugSetup_SetCaptain](https://github.com/splewis/csgo-pug-setup/blob/master/scripting/include/pugsetup.inc#L263) native.
