### ISSUE TITLE
Start everything automatically.

### ISSUE THREAD

**Issue by abhishekdeshkar** [splewis/csgo-pug-setup#191]
Hello,

I'm coming from CS 1.6. And I have automix server which uses PUG plugin of pawn. So that has everything configured automatically. For example, when player connects, they get ready automatically. Team size is fixed and once 10 players are connected it starts match automatically.

Here I in this plugin, I have to do .setup every time to start a match. There should be an option to disable ready system or to ready a player once he/she joins a team. and once 10 players are connected, match should be started automatically. Is that possible with this plugin ?

Thanks!

**Comment by Technoblazed** [comment]
You can have the match settings autosetup using the cvars provided with the plugin, however there is currently not a feature to auto-ready up players. You, or somebody else would need to create a plugin that automatically readies a player up when they join a team.

**Comment by splewis** [comment]
sm_pugsetup_autosetup 1

There's no way to disable ready system, and I don't intend to add one.

**Comment by abhishekdeshkar** [comment]
@splewis  : You should add one then. Because in India we have Automix servers of counter-strike 1.6 and they all have auto ready system so as soon as 10 player joins, the match starts. And everybody is demanding for the auto ready system. :/

**Comment by splewis** [comment]
I'm not going to - the main use case of this project is private servers, not public ones. 

You could write another plugin that auto-redies clients using the [PugSetup_ReadyPlayer](https://github.com/splewis/csgo-pug-setup/blob/master/scripting/include/pugsetup.inc#L225) native pugsetup provides.

Sorry, the ready system isn't going to be changed anytime soon.

**Comment by abhishekdeshkar** [comment]
@splewis   : I understand your concern but can't you give one cvar to autoready system? I'm absolutely not saying to force people to use it. One cvar will be fine :)

**Comment by Technoblazed** [comment]
It's not just a cvar, it either requires a rewrite of the ready system, or a plugin that force readies players when they connect to the server, both of which have been previously stated.

**Comment by Zephyr2323** [comment]
how to do autosetup 😓
