### ISSUE TITLE
knife winning prompt

### ISSUE THREAD

**Issue by AdrianJaniczek** [splewis/csgo-pug-setup#192]
am i able to change the outputted message after winning a knife round from.stay and .swap to .ct and .t
insted?

**Comment by Technoblazed** [comment]
Edit the translation files, it supports that by default.

**Comment by splewis** [comment]
You **can** edit the [translation file](https://github.com/splewis/csgo-pug-setup/blob/master/translations/pugsetup.phrases.txt), but I wouldn't call that "supported".

For example, a new release could add more phrases and you'd be expected to overwrite your changes with the new file.

**Comment by AdrianJaniczek** [comment]
i cannot find the correct line to edit, i want to edit the on screen prompt from " please write .stay or .switch" after winning knife round to "Please write .ct or .t" but i can only see 
"KnifeRoundWinner"
	{
		"#format"	"{1:s},{2:s},{3:s}"
		"en"		"The {1} team won the knife round. Waiting for them to type {GREEN}{2} {NORMAL}or {GREEN}{3}"
	}
	"KnifeRoundWinnerVote"
	{
		"#format"	"{1:s},{2:s},{3:s}"
		"en"		"The {1} team won the knife round. Waiting for them to vote by typing {GREEN}{2} {NORMAL}or {GREEN}{3}"
	}

**Comment by splewis** [comment]
That's the line. just don't use the {2} or {3} args.

`` "The {1} team won the knife round. Waiting for them to type {GREEN}.ct {NORMAL}or {GREEN}.t" ``

Since this isn't a supported change, I'm going to close this. You really shouldn't mess with translation files on your own.
