### ISSUE TITLE
Mapveto BO3

### ISSUE THREAD

**Issue by TGMaster** [splewis/csgo-pug-setup#194]
Could you add mapveto bo3? I tried copying code from warmod but it was failed.
That would be great if there are mapveto bo3, bo5, etc.

**Comment by Technoblazed** [comment]
This is a PUG plugin, if you're looking for something like that, use [get5](https://github.com/splewis/get5)

**Comment by splewis** [comment]
Yeah, what I said in #180 is still accurate. Sorry.
