### ISSUE TITLE
At 15-15 score, Overtime doesn't start

### ISSUE THREAD

**Issue by AzuuraD** [splewis/csgo-pug-setup#195]
### Expected behavior
At 15-15 the game goes to overtime

### Actual behavior
At 15-15 the game freezes on "Overtime Resumes in 00:15" and doesn't continue

### Steps to reproduce
Play a game to 15-15 with mp_overtime_enable 1

- Plugin version: 2.0.2
- Sourcemod version: 1.8.0-git5985

**Comment by Technoblazed** [comment]
Do you have halftime pausing enabled?

**Comment by AzuuraD** [comment]
No, halftime pausing isn't enabled

---- On Mon, 03 Jul 2017 21:51:16 +0000 notifications@github.com wrote ----

Do you have halftime pausing enabled?

**Comment by splewis** [comment]
You likely have one of

``mp_overtime_halftime_pausetimer``
``mp_halftime_pausetimer``

set. Check the values of those cvars. pugsetup itself isn't doing this, you probably have the cvars being set by another plugin or config file somewhere.

**Comment by splewis** [comment]
Closing since there's been no update and I don't believe this is a pugsetup issue.
