### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by punkstarharis** [splewis/csgo-pug-setup#196]
Server is getting crashed when I add pug setup plugin
I was using warmod plugin and everything is going fine but when I add pug setup server getting crash and not starting

**Comment by Technoblazed** [comment]
Update your sourcemod version. This includes all extensions and gamedata

**Comment by punkstarharis** [comment]
Can you pls tell me how to update sourcemod? Should I download newer version from web or any other way?

**Comment by Technoblazed** [comment]
https://wiki.alliedmods.net/Upgrading_sourcemod

**Comment by punkstarharis** [comment]
Im already using sourcemod 1.8 and the error is still there

**Comment by splewis** [comment]
Having "sourcemod 1.8" doesn't mean the gamedata is updated.

Can you give any steps to reproduce? Sourcemod version? plugin version? Does the server work without pugsetup, then crash with pugsetup? Any sourcemod error logs?

**Comment by Technoblazed** [comment]
Here's another link regarding gamedata updates: https://wiki.alliedmods.net/Gamedata_Updating_(SourceMod)

**Comment by punkstarharis** [comment]
Yup server is working with warmod and your retakes plugin

**Comment by splewis** [comment]
You should install this extension to get a crashdump then: https://forums.alliedmods.net/showthread.php?t=277703&

I would also try disabling every other plugin but pugsetup.
