### ISSUE TITLE
Plugin stopped working

### ISSUE THREAD

**Issue by anish58** [splewis/csgo-pug-setup#197]
Plugin stopped working after the recent csgo update. Possible fix please?

**Comment by Technoblazed** [comment]
Please read: https://github.com/splewis/csgo-pug-setup/issues/196

**Comment by splewis** [comment]
I have no reason to believe this has anything to do with pugsetup: https://forums.alliedmods.net/showthread.php?t=300464

If you think something is actually broken, please be more specific.
