### ISSUE TITLE
Help with order of config exec

### ISSUE THREAD

**Issue by spacecow123** [splewis/csgo-pug-setup#198]
If reporting a bug, fill in the following sections:

### Expected behavior
I have rankme enable 1 on the live.cfg but don't want it to count knife rounds 
So I put:
I put in rankme enable 0 on the knife.cfg

rankme enable 1 should run on live.cfg after knife round?

### Actual behavior
Live.cfg runs before knife.cfg but does not run again after knife round? So then rankme enable = 0 still.

Where should I put rankme enable 1 so that it turns on after knife round

**Comment by Technoblazed** [comment]
What's *meant* to happen, is that when the knife config is executed, it takes a backup of the server cvars, then after the knife round is finished, restores the previous cvars.

**Comment by splewis** [comment]
@Technoblazed is correct.

The order is:
- exec live
- exec knife (remember what changed)
- restore the things that knife changed

This has the advantage of not requiring every cvar the knife config changes to also be in the live config.

**Comment by spacecow123** [comment]
I figured out the problem: I put rcon in front of those commands, removing rcon fixed the problem of it not reverting.

Thanks for everyone's help.
