### ISSUE TITLE
Timed Pause / Max Pause

### ISSUE THREAD

**Issue by WardPearce** [splewis/csgo-pug-setup#199]
Hey,
Would I be able to only allow 2 pauses per map & 30 seconds long pauses.

**Comment by splewis** [comment]
Yeah, I don't plan on adding special pause support in this plugin - it's not meant for environments where that kind of pause is used. Get5 supports this: https://github.com/splewis/get5

**Comment by paulocrash** [comment]
This idea will not be made, or the opinion about it has changed, I found this option interesting.

I believe it is perfect if you can control how many pause per map can be used and the time of each pause.

@splewis
