### ISSUE TITLE
Coach not being swapped after kniferound

### ISSUE THREAD

**Issue by SuplenC** [splewis/csgo-pug-setup#200]
### Expected behavior
Coach, setting up "coach t/ct", after winning team doing "!switch" changes the team which is coaching too.

### Actual behavior
Coach remains in the same team while teams swap, spectating the opponent. Therefore it causes him the necessity to reconnect to the server and enter coach again.

### Steps to reproduce
- Plugin version: 2.0.3
- Sourcemod version: Latest

**Comment by splewis** [comment]
This should be already fixed by https://github.com/splewis/csgo-pug-setup/commit/8135fcfd0006d906ecdbbbf8c141e251fcdf626a, it's just not in a release yet.
