### ISSUE TITLE
Accidental Team Killing

### ISSUE THREAD

**Issue by RaiidCS** [splewis/csgo-pug-setup#203]
Hello, I was playing a 10man and on one round, one of our teammates accidentally killed another. PugSetup then decided to kill the player after that round ended and not allow him to play the new round.
I want to know how to disable this. How can I do so?

- Plugin version: Latest
- Sourcemod version: Latest

**Comment by Technoblazed** [comment]
1) Please don't use `Latest` as a version, it's absolutely useless.
2) This isn't a PugSetup issue, check your value of `mp_tkpunish`. It should be set to zero. Alternatively you may have other plugins installed causing your issue.

**Comment by splewis** [comment]
This definitely isn't pugsetup doing it. Either another plugin or some game cvar like techo said.
