### ISSUE TITLE
Reloading map for GOTV without warmup.

### ISSUE THREAD

**Issue by MichalLauer** [splewis/csgo-pug-setup#204]
It would be cool if you could have an option that when everybody readys up, the map will reload and start the GOTV Recording. With this, you could have gotv just of the match, not the actuall warmup.
Ofcourse, after the reload, everybody would have to type .ready once again, but it's worth the free-warmup demo (or, you can type .forcestart OR it would start automaticly with some magic power)

**Comment by splewis** [comment]
Sorry, while possible I don't think this feature would be worth adding.
