### ISSUE TITLE
SRCDS Crashing with this plugin

### ISSUE THREAD

**Issue by punkstarharis** [splewis/csgo-pug-setup#205]
Hello, my csgo server is crashing with this plugin working fine with other plugins like retakes, warmod also i have added steamworks extension for this plugin and i dont know why its still crashing im attaching a video of this pls help me 

https://youtu.be/2urtC_EXvNw

**Comment by Technoblazed** [comment]
Error logs? Version? Come on, at least give some information.

**Comment by punkstarharis** [comment]
@Technoblazed from where i can get log files & Sourcemod Version is 1.8

**Comment by Technoblazed** [comment]
- /addons/sourcemod/logs
- Plugin version pls
- Sourcemod 1.8 has thousands of versions. Run ‘sm version’

**Comment by punkstarharis** [comment]
Log file dont have any log about this plugin 
Plugin version is the latest one i have downloaded from github
SourceMod Version: 1.8.0.5985
             SourcePawn Engine: SourcePawn 1.8, jit-x86 (build 1.8.0.5985)
             SourcePawn API: v1 = 4, v2 = 11
             Compiled on: Apr 26 2017 03:52:26
             Built from: https://github.com/alliedmodders/sourcemod/commit/6b5faff
             Build ID: 5985:6b5faff
             http://www.sourcemod.net/

**Comment by punkstarharis** [comment]
Plugin Version : 2.0.3

**Comment by splewis** [comment]
Install accelerator and get a crash dump: https://forums.alliedmods.net/showthread.php?t=277703

It's probably not from pugsetup though. The crash dump will probably help you find out, though.

**Comment by punkstarharis** [comment]
-------- CONFIG BEGIN --------
Map=
GamePath=E:\CSGO-Servers\Automix\csgo
CommandLine=E:\CSGO-Servers\Automix\srcds.exe  -console -game csgo -usercon -autoupdate +game_type 0 +game_mode 1 +mapgroup mg_active +map de_mirage -net_port_try 2 +ip 119.63.128.154 +port 27052 -tickrate 128
SourceModPath=E:\CSGO-Servers\Automix\csgo\addons\sourcemod
GameDirectory=csgo
ExtensionVersion=2.3.3
ExtensionBuild=94:e01565f
Steam_ClientVersion=649
Steam_ServerVersion=649
Steam_PatchVersion=1.36.2.4
Steam_ProductName=csgo
Steam_appID=730
Steam_SourceRevision=4337704
Steam_VersionDate=Jan 29 2018
Steam_VersionTime=14:55:52
-------- CONFIG END --------
-------- CONSOLE HISTORY BEGIN --------
25(1.768305):  Accelerator upload thread terminated. (canceled = false)
24(1.767733):  Accelerator upload thread finished. (0 uploaded, 0 failed)
23(1.767028):  Accelerator upload thread started.
22(1.761913):  L 01/30/2018 - 10:46:37: -------- Mapchange to de_mirage --------
21(1.760842):  Host_NewGame on map de_mirage
20(1.068220):  ---- Host_NewGame ----
19(1.055771):  Cannot init steam datagram client, no Steam HTTP interface
18(1.055190):  Cannot init steam datagram client, no Steam HTTP interface
17(1.053280):  Unknown command "port"
16(1.052545):  Setting mapgroup to 'mg_active'
15(1.051737):  Unknown command "cl_teamid_overhead_maxdist"
14(1.051322):  Unknown command "cl_teamid_overhead"
13(1.050639):  Unknown command "cl_teamid_max"
12(1.050028):  Unknown command "cl_teamid_min"
11(1.049313):  Unknown command "cl_viewmodel_shift_right_amt"
10(1.048612):  Unknown command "cl_viewmodel_shift_left_amt"
9(1.047787):  Unknown command "cl_bob_lower_amt"
8(1.047223):  Unknown command "cl_bobamt_lat"
7(1.046525):  Unknown command "cl_bobamt_vert"
6(1.045347):  ConVarRef cl_embedded_stream_video_playing doesn't point to an existing ConVar
5(0.635371):  maxplayers set to 64
4(0.562038):  No web api auth key specified - workshop downloads will be disabled.
3(0.559518):  Particles: Missing 'particles/money_fx.pcf'
2(0.433819):  Server is hibernating
1(0.433101):  Failed to load gamerulescvars.txt, game rules cvars might not be reported to management tools.
-------- CONSOLE HISTORY END --------

**Comment by punkstarharis** [comment]
@splewis @Technoblazed  ??

**Comment by Technoblazed** [comment]
Link the accelerator crash dump.

**Comment by punkstarharis** [comment]
[87a23484-0240-4537-9cec-ad972aba22cf.dmp.txt](https://github.com/splewis/csgo-pug-setup/files/1684350/87a23484-0240-4537-9cec-ad972aba22cf.dmp.txt)

**Comment by splewis** [comment]
Pasting your server console log is not the same thing as a crash dump (that's pretty useless).

The accelerator sourcemod extension uploads a crash dump, then you can get a link from https://crash.limetech.org/ (if you set the MinidumpAccount value like the installation instructions describe).

 However the web server currently isn't accepting crash dumps (https://forums.alliedmods.net/showthread.php?p=2573357#post2573357), so it might be a little while before we can get a crash dump link. Until then there's nothing worth me investigating here.

**Comment by punkstarharis** [comment]
@splewis 
![untitled](https://user-images.githubusercontent.com/28386395/35663789-de039174-0740-11e8-916a-886c4a5ea703.png)

**Comment by splewis** [comment]
That still isn't a link to the actual crash dump...

but the fact it says "SteamWorks.ext.dll" means it's a Steamworks problem. Either get rid of the Steamworks or report the issue @ https://forums.alliedmods.net/showthread.php?t=229556

**Comment by punkstarharis** [comment]
here is the link of minidump file
https://drive.google.com/file/d/1SIeE82RvLHbxcwjPZe4ueTcmnosCeWr0

**Comment by Technoblazed** [comment]
Please refer to splewis' previous post. Either get rid of the Steamworks or report the issue @ https://forums.alliedmods.net/showthread.php?t=229556

**Comment by punkstarharis** [comment]
Its working now after removing steam works extension 
thnkx for your @Technoblazed  @splewis  <3
![20180201112904_1](https://user-images.githubusercontent.com/28386395/35664278-2f7817bc-0743-11e8-8953-e0e968f3c07e.jpg)
