### ISSUE TITLE
Not changing to workshop maps via map vote

### ISSUE THREAD

**Issue by captainswain** [splewis/csgo-pug-setup#207]
### Expected behavior
When voting for a map changelevel should swap you to the selected map.

### Actual behavior
Upon map vote of any non-default map the map never changes.

### Steps to reproduce
- Plugin version:2.0.3
- Sourcemod version:1.8
- LGSM for the base server.

This post outlines the issue more or less:
https://forums.alliedmods.net/showthread.php?t=246884

Note: I'm using the Steamworks extension and using workshop collection ID for my map list. 

I also have subscribed_collection_ids.txt loaded as well as subscribed_file_ids.txt with the correct ids.

**Comment by Technoblazed** [comment]
1) Please don't use `latest` as a version. It's unbelievably vague. Go find the ACTUAL versions you're using.

**Comment by captainswain** [comment]
Updated

**Comment by Technoblazed** [comment]
Version 2.0.3 is over 9 months old. Either compile it from the source yourself, or download the latest dev build from here https://ci.splewis.net/job/csgo-pug-setup/lastSuccessfulBuild/

**Comment by captainswain** [comment]
Downloading and testing on this development build. I will report back!

**Comment by splewis** [comment]
There's no need to use a newer build here. It won't help.

This is probably not a pugsetup problem, it's an annoyance of the game - that alliedmodders thread explains it. Usually users delete those 2 files and use launch options to specify the workshop collection and default map.

I'd suggest trying to run ``rcon host_workshop_map 12345679`` (replacing the number with the actual map id) on your server to test. Executing that command is all pugsetup does.

**Comment by captainswain** [comment]
Hi,

I've removed those 2 files and set my launch options to the workshop collection and default map. however, I can't seem to get host_workshop_map to work?

Do I need to remove any of my SM files or simply the subscribed files?

my start command:
> ./srcds_run -game csgo -usercon -strictportbind -ip {redacted} -port 27015 +clientport 27005 +tv_port 27020 +sv_setsteamaccount {redacted} -tickrate 128 +servercfgfile csgoserver.cfg -maxplayers_override 10 +mapgroup mg_active +game_mode 0 +game_type 0 +host_workshop_collection 1298049129 +workshop_start_map 122443683 -authkey {redacted} -nobreakpad


My apologies for the issues.

Thanks for such swift replies!

**Comment by splewis** [comment]
I have no other ideas why host_workshop_map doesn't work for you, and I don't think pugsetup is related at all.

You're probably better off asking somewhere for srcds in general, like https://forums.alliedmods.net/forumdisplay.php?f=130

**Comment by Technoblazed** [comment]
I've had this happen before and it's honestly just random, there's no reproducible steps, restart your server and try again.

**Comment by captainswain** [comment]
Hi,

This has somewhat been fixed by removing the map switch plugin!


What is the recommended setup? simply load the bsp files up on the server?

**Comment by Technoblazed** [comment]
Either use workshop, or add the bsp files on the server and setup a fastdl if you’re using custom maps

**Comment by splewis** [comment]
You can load maps however you want. I don't think there's anything pugsetup can do here.
