### ISSUE TITLE
Unknown command "sm_pugsetup_use_aim_map_warmup"

### ISSUE THREAD

**Issue by at0mzk1** [splewis/csgo-pug-setup#208]
### Expected behavior

Server should change to a hosted aim_map defined in the aim_maps.txt file while starting warmup.

### Actual behavior

Plugin doesn't recognize this convar. When the plugin autogenerates `pugsetup.cfg` file it does not contain this convar, and adding it results in the error displayed in the title of this issue.

(Also, there's an error in the documentation under the conVar section, it is created under `cfg/sourcemod/pugsetup/` and **not** under `cfg/sourcemod/`)

### Steps to reproduce
- Plugin version: 2.0.4
- Sourcemod version: 1.8.0.6041

1. Download PugSetup plugin and all dependencies.
2. Start your server (pugsetup.cfg will be generated).
3. Stop your server.
4. Navigate to `cfg/sourcemod/pugsetup/`.
5. Edit `pugsetup.cfg` and add `sm_pugsetup_use_aim_map_warmup "1"` at the end (As it wasn't automatically generated)
6. Save and close and start your server again.

**Comment by Technoblazed** [comment]
`sm_pugsetup_use_aim_map_warmup` is no longer used as far as I can tell. Assuming you have maps inside `/addons/sourcemod/configs/pugsetup/aim_maps.txt`, the maps are actually installed onto the server, and inside `/addons/sourcemod/configs/pugsetup/setupoptions.cfg`, you have the `aimwarmup` key set to 1, should work fine ;)

**Comment by Technoblazed** [comment]
#209

**Comment by at0mzk1** [comment]
Thank you, this solves my issue.
