### ISSUE TITLE
kick bot after switch team in warmup

### ISSUE THREAD

**Issue by ilyasafr** [splewis/csgo-pug-setup#210]
can u kick/disable bot when player switch team to ct/t in warmup

**Comment by Technoblazed** [comment]
bot_quota 0
bot_join_after_player 0

Alternatively, search for ‘no bot enforcer’ in google

**Comment by splewis** [comment]
You can set whatever bot-related cvars you want in your warmup config.

**Comment by borzaka** [comment]
These commands in the `warmup.cfg` are **not working**:
```
bot_quota 0
bot_join_after_player 0
```

Bots are keep joining as I change team.

Ultimate solution: add `-nobots` to your server start parameters.
