### ISSUE TITLE
Demo name format

### ISSUE THREAD

**Issue by welele** [splewis/csgo-pug-setup#211]
Hello, our team is currently using this plugin for practice. We prefer this over ebot because it's easier to setup. However, the demo names are a bit confusing when we play a lot of matches and want to find a specific demo.
So my question is, how do I change de demo name format to have the team names? Also, how do I a format the date to: Hour:Minute_Day/Month/Year

Thank you for the help

**Comment by splewis** [comment]
From the readme:

> sm_pugsetup_demo_name_format (default "pug_{MAP}_{TIME}") - Naming scheme for demos. You may use {MAP}, {TIME}, and {TEAMSIZE}. Make sure there are no spaces or colons in this
sm_pugsetup_time_format (default "%Y-%m-%d_%H") - Time format to use when creating demo file names.

I would also strongly suggest not trying to name it with colons or slashes.
