### ISSUE TITLE
Enable Retake in Aim Maps (explained)

### ISSUE THREAD

**Issue by luckykev** [splewis/csgo-pug-setup#213]
I am trying to enable retakes **only** in warmup (**before the game starts** and a map is voted, whilst people are readying up). I do not want retakes enabled while captains are picking teams - this causes issues with team selection.

To do this I am trying to use the "aim map warmup" feature.

Desired function: when I restart the server, retakes should be enabled. When a map is voted on and changed, retakes is disabled.

### Expected behavior

I enable the setup options to use aim maps in warmup. I have the aim maps set to use a Steam Workshop collection of normal maps (de_cache, de_overpass, etc.) that work with retakes.

I want retakes to be enabled only during the "aim map warmup", but when everyone ready's up and votes for a map, retakes is not enabled on that voted map during team selection.

### Actual behavior

I've gotten retakes enabled during aim map warmup, however, every time the round restarts, mp_warmup_pausetimer is forced to 1. When I turn mp_warmup_pausetimer to 0, normal retake warmup countown begins and the players spawn in their retake spawns. A second later, mp_warmup_pausetimer is forced back to 1 and the game is stuck in warmup mode.

When I go into .setup and disable "aim map warmup" and turn mp_warmup_pausetimer to 0, retakes functions normally.

### Steps to reproduce
- Plugin version: Latest
- Sourcemod version: Latest

**Comment by luckykev** [comment]
@splewis @Technoblazed Any suggestions?

**Comment by splewis** [comment]
> Steps to reproduce
Plugin version: Latest
Sourcemod version: Latest

...

If warmup is turning on when you don't want it to, you can try setting sm_pugsetup_use_game_warmup. Otherwise I'd consider doing something other than "aim map warmup" in "aim map warmup" unsupported.

**Comment by luckykev** [comment]
@splewis sm_pugsetup_use_game_warmup 0 doesn't work. Please let me know if you have any other suggestions. If not np just thought I'd ask. Thanks for getting back to me!
