### ISSUE TITLE
Deathmatch as warmup

### ISSUE THREAD

**Issue by cycloidsoftware** [splewis/csgo-pug-setup#214]
During the first warmup (the warmup that the map vote takes place in), it would be cool to have an option to play deathmatch as warmup.  Lots of people in the PUG server I run have requested this feature, I think it would be awesome.

**Comment by spacecow123** [comment]
It is implemented already, use the aim warmup option.

**Comment by cycloidsoftware** [comment]
My bad, I'll check it out.  Thanks!
