### ISSUE TITLE
Questions about permissions and demo name formatting

### ISSUE THREAD

**Issue by vtrbh** [splewis/csgo-pug-setup#215]
Is it possible to format the demo name with the teams name? for example mapname_team_captain1_vs_team_captain2_timestamp.dem

so if the team uses a team tag it would use the team tag name, if they dont, use captain name, if they dont use any of this maybe a random name from each team.

Another question, how can i set sm_setup to be able only to players logged with rcon password? tried to set sm_setup to "admin" instead of "all" in permissions.cfg but didnt work(i think admin setting is for admins mentioned in admins_simple file..)

Thanks!

**Comment by splewis** [comment]
No, you can't use team names in ``sm_pugsetup_demo_name_format``. You could potentially write another plugin that sets that cvar, but it would have to figure out the teamnames itself.

You can set the admin permissions to "none", and the [server](https://github.com/splewis/csgo-pug-setup/blob/master/scripting/pugsetup/natives.sp#L382) will still be able to run the command (so rcon should work).
