### ISSUE TITLE
Bug Prefix

### ISSUE THREAD

**Issue by peralta00** [splewis/csgo-pug-setup#218]
For some reason the first char of the prefix is not being affected by the color tags.

my config:
`sm_pugsetup_message_prefix "{LIGHT_RED}[{DARK_RED}TAG{LIGHT_RED}]{NORMAL}"`

### Expected behavior

Tag: dark red
Brackets: light red
Text: normal

[TAG] test

### Actual behavior

Tag: dark red
Brackets: light red (the first one stays white)
Text: normal

[TAG] test

### Steps to reproduce
- Plugin version: 2.0.4
- Sourcemod version: 1.8.0.6040

**Comment by splewis** [comment]
It's a limitation of csgo. If you add a space to the front it will probably work:

``sm_pugsetup_message_prefix " {LIGHT_RED}[{DARK_RED}TAG{LIGHT_RED}]{NORMAL}"``

**Comment by peralta00** [comment]
Ok, i will try that as soon as possible ;)

thanks.

**Comment by splewis** [comment]
I'm going to close this. It's more of a CS:GO issue I'm not planning on working around in the code.
