### ISSUE TITLE
Server crashing with pugsetup plugin while opting into -panorama

### ISSUE THREAD

**Issue by luckykev** [splewis/csgo-pug-setup#221]
### Expected behavior
Users being able to join the server

### Actual behavior
Server gets stuck on the loading screen while opted into -panorama
Disabling pugsetup.smx allows users to join on -panorama
It's none of the supporting pugsetup plugins (process of elimination disabling plugins)

### Steps to reproduce
- Plugin version: 2.0.3-dev
- Sourcemod version: 1.9.0.6241
- Steps to reproduce (please be specific):
Add '-panorama' to launch settings in CSGO
Join server

**Comment by punkstarharis** [comment]
same happening with me @splewis  please help

**Comment by punkstarharis** [comment]
@Technoblazed

**Comment by splewis** [comment]
> Server gets stuck on the loading screen

If you have server crashes you should get a crash dump using [Accelerator](https://forums.alliedmods.net/showthread.php?t=277703&).

> Plugin version: 2.0.3-dev

It's almost certainly unrelated to any issue you have, but please tell me a build number or a commit in the future.

**Comment by splewis** [comment]
https://github.com/splewis/csgo-pug-setup/issues/226
