### ISSUE TITLE
cant join server with -panorama when using Pug Setup Plugin (Client Stuck on loading)

### ISSUE THREAD

**Issue by punkstarharis** [splewis/csgo-pug-setup#225]
When someone try to join server with -panorama there client will be stucked on loading

But

When i remove pug setup plugin then everything goes fine without any stuck or error

### Steps to reproduce
- Plugin version: pugsetup_2.0.4 
- Sourcemod version: 1.9 Build 6245
- Steps to reproduce (please be specific):

**Comment by splewis** [comment]
Closing as a duplicate of https://github.com/splewis/csgo-pug-setup/issues/226.
