### ISSUE TITLE
[REQUEST] Play all 30 rounds

### ISSUE THREAD

**Issue by SuplenC** [splewis/csgo-pug-setup#227]
Hi splewis
I use this awesome mod during my practice matches against other teams. One thing is lacking in that mod is a feature to play all 30 rounds, it would be setting in second half the command "mp_match_can_clinch 0", so you can play both sides 15 rounds.
Thanks

**Comment by Technoblazed** [comment]
Add it to your own live.cfg

**Comment by splewis** [comment]
You can add it to the setup menu (and change the default) here:

https://github.com/splewis/csgo-pug-setup/blob/master/configs/pugsetup/setupoptions.cfg#L50

**Comment by ZIODIOZIO** [comment]
how can be added?

**Comment by ZIODIOZIO** [comment]
@splewis

**Comment by FuveZeq** [comment]
@ZIODIOZIO 
	"playout"
	{
		"default"		"0"
		"display_setting"		"0" <---- set to 1 and  server restart, if done u can see in menu "playout max rounds"
	}
sry for bad english xD
