### ISSUE TITLE
Chat Aliases as separated plugin

### ISSUE THREAD

**Issue by SuplenC** [splewis/csgo-pug-setup#234]
I set up some aliases that I wanted to be executed with .command, my problem is that one of them unloads the PUG Setup plugin to load another plugin. Is there a possibility to have chat aliases as a different smx, or maybe there was already a plugin or way to introduce custom commands?

**Comment by splewis** [comment]
Sorry, I don't think it's worth making another plugin for this. I don't know of other plugins.
