### ISSUE TITLE
After 10 players type !ready, it no longer counts the players that type !ready

### ISSUE THREAD

**Issue by crashzk** [splewis/csgo-pug-setup#238]
### Expected behavior
The players that enter the server after the captains are already choosing the teams, their nick is not in the list, because they were not on the server, and even those who did not type .ready is not in the list to be chosen.

In case even if they do not type .ready, or enter the server when they are already choosing the players for the teams their nicks should appear in the list automatically or if they type the .ready.

### Actual behavior
After all 10 players type `.ready` there are only 10 players who have typed to choose, if you have spec that did not give .ready or if the player enters the server at the time you are choosing the players for the team his nickname does not appears in the list even by typing .ready.

### Steps to reproduce
Just connect to the server and stay spec and not enter .ready, when the competitive player nickname does not start .ready does not show in the list. And like I said, even if the player connects on the server during the process of choosing the times.

@splewis

**Comment by splewis** [comment]
I don't really understand this. Are you aware of the ``sm_pugsetup_exclude_spectators`` cvar?

**Comment by paulocrash** [comment]
> Well, if 10 players readied and the picking began, then a random 11th joined, it's working-as-intended if that 11th didn't show up on the player-picking list.

This, in case this 11th does not appear in the list, it would be possible to have the nick appear on the list, even though it did .ready after the other 10 players.

**Comment by splewis** [comment]
If a player wasn't ready when the game "began", I don't see why they should appear on the list. Maybe I haven't understood the issue still, though.
