### ISSUE TITLE
"mp_give_player_c4 1" is missing in live.cfg

### ISSUE THREAD

**Issue by borzaka** [splewis/csgo-pug-setup#240]
### Expected behavior
`live.cfg` should cointain `mp_give_player_c4 1`, as stated in the [readme](https://github.com/splewis/csgo-pug-setup#configuration):

> By default the plugin uses the ``cfg/sourcemod/pugsetup/live.cfg`` config when going live. You are free to change this file all you want (or change which file is used via the ``sm_pugsetup_live_cfg`` cvar). (Note: if you use knife rounds, make sure ``mp_give_player_c4 1`` is in this file!)

I want to use knife rounds.

### Actual behavior
`mp_give_player_c4 1` is not in `live.cfg`, so it's probably breaking the game (haven't tested, assumption only based on the source code and readme).

I would like to use `esl5on5.cfg` insted of `live.cfg`, so I should add `mp_give_player_c4 1` there as well and exec it instead of `live.cfg`?

**Comment by splewis** [comment]
The cvar isn't needed since when the knife config is executed, the cvars it sets are saved before execution then restored when the knife round finishes. 

The README is out of date, although it's still good practice to have that cvar in the live config.
