### ISSUE TITLE
sm_forcestart not force starting the match

### ISSUE THREAD

**Issue by borzaka** [splewis/csgo-pug-setup#241]
```
● (Counter-Terrorist) Attila‎ @ CT Start :  .setup
[PugSetup] Pug leader: Attila
[PugSetup] Map type: use the current map
[PugSetup] Team type: (5 vs 5) manually switch
[PugSetup] Record demo: enabled
[PugSetup] Knife round: enabled
[PugSetup] Autolive: enabled
[PugSetup] You don't have permission to do that.
```

### Expected behavior
Force starting the match.

### Actual behavior
Not force starting the match:
> You don't have permission to do that.

### Steps to reproduce
1. `.setup` a match
2. finish the setup
3. enter `sm_forcestart` in the console
4. You will get
> You don't have permission to do that.

- Plugin version:
```
] sm plugins
 "Basic Info Triggers" (1.9.0.6256) by AlliedModders LLC
 "Player Commands" (1.9.0.6256) by AlliedModders LLC
 "Basic Votes" (1.9.0.6256) by AlliedModders LLC
 "Reserved Slots" (1.9.0.6256) by AlliedModders LLC
 "Admin File Reader" (1.9.0.6256) by AlliedModders LLC
 "Admin Help" (1.9.0.6256) by AlliedModders LLC
 "Client Preferences" (1.9.0.6256) by AlliedModders LLC
 "Nextmap" (1.9.0.6256) by AlliedModders LLC
 "Sound Commands" (1.9.0.6256) by AlliedModders LLC
 "Basic Ban Commands" (1.9.0.6256) by AlliedModders LLC
To see more, type "sm plugins 11"
] sm plugins 11
 "Fun Commands" (1.9.0.6256) by AlliedModders LLC
 "Anti-Flood" (1.9.0.6256) by AlliedModders LLC
 "CS:GO PugSetup" (2.0.5) by splewis
 "Admin Menu" (1.9.0.6256) by AlliedModders LLC
 "Basic Commands" (1.9.0.6256) by AlliedModders LLC
 "Fun Votes" (1.9.0.6256) by AlliedModders LLC
 "Basic Chat" (1.9.0.6256) by AlliedModders LLC
 "Basic Comm Control" (1.9.0.6256) by AlliedModders LLC
```

- Sourcemod version:
`sourcemod-1.9.0-git6256`

-Metamod version:
`mmsource-1.10.7-git966`

**Comment by Technoblazed** [comment]
Well as it says, you don't have permission to do that. Make sure your `/addons/sourcemod/configs/pugsetup/permissions.cfg` is configured correctly, and that you have the appropriate permissions if it's set to admin only.

**Comment by borzaka** [comment]
Sorry, my bad. I thought I have admin, but I reinstalled source and metamod and my admin was gone, I had to configure again.

I had to add myself as admin here:
`csgo/addons/sourcemod/configs/admins_simple.ini`
