### ISSUE TITLE
Match can clinch stay activated

### ISSUE THREAD

**Issue by Raphiy** [splewis/csgo-pug-setup#244]
Hey Buddy,
i am using your really nice plugin for the cs server of my team.
now we want to play some pugs where we have the ability to play all 30 rounds.
I insertert the command "mp_match_can_clinch 0" in live.cfg but it doesnt work.
I also tried to put it in the server.cfg.
Do you have any ideas why this is happening? If i change the command ingame during a pug,
it works fine.
Have a nice week!!
Greetings from Germany.

Raphiy

PS. sorry for my bad english skills

**Comment by splewis** [comment]
You can enable the option to playout the maxrounds in configs/pugsetup/setupoptions.cfg: https://github.com/splewis/csgo-pug-setup/blob/master/configs/pugsetup/setupoptions.cfg#L47

pugsetup will automatically set mp_match_can_clinch based on this setting.

**Comment by Raphiy** [comment]
Thank you very much for your help and the pretty fast support!! :)
