### ISSUE TITLE
There is no .forcestart command for sm_forcestart

### ISSUE THREAD

**Issue by borzaka** [splewis/csgo-pug-setup#245]
But for `sm_forceend` there is a `.forceend`

**Comment by splewis** [comment]
Sorry, I think there is a .forcestart command supported in chat.

https://github.com/splewis/csgo-pug-setup/blob/master/scripting/pugsetup.sp#L371
https://github.com/splewis/csgo-pug-setup/blob/master/scripting/pugsetup.sp#L478

**Comment by borzaka** [comment]
My mistake, probably miss-typed. Sorry.

Only one scenario, when it's not working: after .forceend
After .forceend, you can't use .forcestart, it does nothing.

**Comment by splewis** [comment]
> After .forceend, you can't use .forcestart, it does nothing.

That's because there's no game setup.

**Comment by borzaka** [comment]
Even with `sm_pugsetup_autosetup "1"`?

Or`sm_pugsetup_force_defaults "1"` would needed for this?

My current settings:
- `sm_pugsetup_autosetup "1"`
- `sm_pugsetup_force_defaults "0"`

**Comment by SuplenC** [comment]
After `.forceend` you should type `.setup`, press 1 and after that `.forcestart`. As an alternative you can use a command `sm_setup`
