### ISSUE TITLE
Add message after map vote when changing to the voted map

### ISSUE THREAD

**Issue by borzaka** [splewis/csgo-pug-setup#250]
`[PugSetup] de_dust2 won, de_cache came in 2nd, de_nuke in 3rd`

After this message and a couple of seconds a map change will occour.

It would be nice to see this in progress:
Changing map to de_dust2, or something like this.

**Comment by Technoblazed** [comment]
This already occurs here: https://github.com/splewis/csgo-pug-setup/blob/475eae976d2feb568f79d1eea9a0437d0890ead0/scripting/pugsetup/maps.sp#L11

**Comment by borzaka** [comment]
Well, there was no message seen before mapchange.

**Comment by borzaka** [comment]
Sorry, my mistake. The message is there, but before the voting results, not after. Closing.
