### ISSUE TITLE
[Feature Request] Automatic ban on which to leave during the competitive

### ISSUE THREAD

**Issue by paulocrash** [splewis/csgo-pug-setup#251]
Option to apply an automatic ban on players leaving the game during the competitive period.

# How will it work?
After the match starts, if any player leaves the match during the live he takes ban.

It would be perfect if you have options so we can set the ban time and why.

**Comment by splewis** [comment]
I don't intend on this being added to pugsetup. The main purpose of pugsetup is for "small" communities/friends, not a pub server or a matchmaking system.

Of course, it's possible to implement outside pugsetup via some of the api it exposes: https://github.com/splewis/csgo-pug-setup/blob/master/scripting/include/pugsetup.inc, but I won't add anything similar to that in this project.
