### ISSUE TITLE
Can't buy as Terrorist

### ISSUE THREAD

**Issue by Nachtfrische** [splewis/csgo-pug-setup#254]
### Expected behavior
At the start of the round (both live and warmup) each player should be able to buy. 

### Actual behavior
While the CT Team can buy just fine, the T Team can't, since the buy wheel is not opening. If you use the console to buy a weapon, you'll get the following output: 
`**** Unable to localize '#Cstrike_TitlesTXT_Terrorist_cant_buy' on panel 'HintLabel'`

The maps are normal and have buyzones. I've tested it on de_inferno and de_dust2 and both show this behaviour. 
mp_humanteam is set to any.

### Steps to reproduce

Please note that "latest" is NOT a version! Run "sm plugins" in console to find out the exact plugin version.

- Plugin version: "CS:GO PugSetup" (2.0.5) by splewis
- Sourcemod version: SourceMod 1.9.0.6254
- Steps to reproduce (please be specific):
1. Be in T-Team 
2. Try to open the buy menu

**Comment by Technoblazed** [comment]
This doesn't seem like anything to do with this plugin. Check that `sv_buy_status_override` is set to `0`.

**Comment by Nachtfrische** [comment]
You're right, I'm sorry. There was a mistake in my server.cfg and I didn't notice it. Google came out empty as well. Thanks for the help.
