### ISSUE TITLE
ReadyStatus newer shows 10 out of 10 players are ready

### ISSUE THREAD

**Issue by borzaka** [splewis/csgo-pug-setup#256]
### Expected behavior
When 10 players are ready, this alert message should shown:
> 10 out of 10 players are ready

### Actual behavior
When 9 players are ready 
> 9 out of 10 players are ready

When the 10th player is ready up, still this shown:
> 9 out of 10 players are ready

### Steps to reproduce
- Plugin version: "CS:GO PugSetup" (2.0.5) by splewis
- Sourcemod version: SourceMod 1.9.0.6260, by AlliedModders LLC

### Additional info:
There were one Spectator, and the 10 players, but `sm_pugsetup_exclude_spectators` was set to `"1"`.
But even without any Spectator, the issue is still present.

**Comment by splewis** [comment]
This is because the "9/10 ready" hint text doesn't get cleared (or set to a 10/10 hint text) after the 10th player readies up. Spectators are irrelevant.

**Comment by borzaka** [comment]
> Highly unlikely.

Sorry to hear that. I really like your plugin, hope you can check and approve my PR.

**Comment by splewis** [comment]
Changed in #257
