### ISSUE TITLE
After a successful map vote, the setup still shows 'vote for a map' on the new map

### ISSUE THREAD

**Issue by borzaka** [splewis/csgo-pug-setup#259]
### Expected behavior
After the successful map vote and changing to it, the setup should show: `Map type: use the current map`

### Actual behavior
On the voted new map the setup still shows: `Map type: vote for a map`
Regardless this, the match starts on the current map correctly.

### Steps to reproduce
- Plugin version: "CS:GO PugSetup" (2.0.5) by splewis
- Sourcemod version: SourceMod 1.9.0.6260, by AlliedModders LLC

1. setup with Map type: vote for a map
2. (force)start the match, vote, and wait for the voted map to load
3. check the setup on the new map, it will still show 'vote for a map'
4. (force)start the match, the match will start on the current (voted) map (which is correct, but the setup shows differently, which is misleading)

I'am using `sm_pugsetup_autosetup 1` and `sm_pugsetup_force_defaults 1`

**Comment by borzaka** [comment]
@splewis Do you need more info about this issue? What can I do to help you identify the root cause?

**Comment by splewis** [comment]
This isn't really a bug. The map type for the pug was to use a map vote, and that's why it's showing that. Just because the map vote already happened doesn't change the parameters of the setup. I can see how it's a little misleading to some, but I don't really think a change is warranted.
