### ISSUE TITLE
Captain pick bug or setting not sure

### ISSUE THREAD

**Issue by abdulsami34** [splewis/csgo-pug-setup#261]
Hello there,
We start a match using .setup then select captain we ready up the captain selection starts but when everyone in spec can join any team like T or CT and that create problems. I have seen a server where the spectate one could not join any team unless captain picks them. 

Is this a bug or is there a cvar for this?

Plugin Version :  2.0.5
SM Version :  1.9 - build 6267

**Comment by splewis** [comment]
That's working as intended. Team joins are only ever blocked if you use the `pugsetup_teamlocker` addon plugin.

**Comment by abdulsami34** [comment]
still happening.
I installed the team locker plugin as well. Players can join teams when the match is live.

**Comment by splewis** [comment]
Duplicate of #236
