### ISSUE TITLE
pugsetup_damageprint

### ISSUE THREAD

**Issue by bartekgazel** [splewis/csgo-pug-setup#265]
Hi.
I dont know why but this plugin is not working on my servers. Do I need pugsetup to work pugsetup_damageprint ?

csgo_damageprint is working but pugsetup_damageprint is not working
I wanna a colors in msg, pls help me.
Maybe you can send me a full compiled plugin pugsetup and pugsetup_damageprint ? 
I cant compile pugsetup cuz of SteamWorks error....
Sorry for my weak english :D

**Comment by borzaka** [comment]
**pugsetup_damageprinter** is an optional plugin, which is not enabled by default in _csgo-pug-setup_.
To enable, you have to move from _plugins/disabled_ folder to _plugins_.

After enable (and a server restart), you can edit this config file: _cfg/sourcemod/pugsetup_damageprint.cfg_
Where you can find the var to enable colors: `sm_pugsetup_damageprint_auto_color`

You don't need to compile anything, unless you want something to modify which can't be achieved with editing the default cfg.

**Comment by splewis** [comment]
You need pugsetup for any of the optional plugins.

**Comment by Technoblazed** [comment]
The non pugsetup version is here: https://github.com/splewis/sm-misc/blob/master/scripting/csgo_damageprint.sp
