### ISSUE TITLE
Autokicker, allow coaches/spectators to connect

### ISSUE THREAD

**Issue by usernameproof** [splewis/csgo-pug-setup#268]
As of right now, a coach connecting when a game is live gets kicked. 

Can we get an option; "Only kick clients after they join a team(T or CT), do not kick clients connecting and/or joining spectators"

Thanks

**Comment by splewis** [comment]
Coaching support is pretty much out of scope for pugsetup entirely. Get5 is intended to support actual competitive usage.

I also don't see how this would work well, it'd have to arbitrarly let all players connect then, in akward limbo state on connect.
