### ISSUE TITLE
Scoreboard-bug after halftime

### ISSUE THREAD

**Issue by Raphiy** [splewis/csgo-pug-setup#269]
### Actual behavior
Hey Buddy,
since i use pugsetup, i'm really liked it. But sometimes we have a little problem after the halftime.
The scoreboard is stuck on the screen of some players and didn't disappear. 
I'm not 100% sure if its from pugsetup/practicmode but we dont use any other plugins on the server.
Maybe you know about this problem or have a clue what it is about. Thanks for your help!!

### Steps to reproduce
We just played and sometimes it happened after the halftime.
We're using only pugsetup and practice mode in combination with the esl 5on5 config.

- Plugin version: 2.0.5
- Sourcemod version: 1.9 - build 6275:
- Steps to reproduce (please be specific):

**Comment by borzaka** [comment]
I know this issue, and it's related to ESL's `esl5on5.cfg`. This is the problematic line:
`mp_win_panel_display_time 15	                // The amount of time to show the win panel between matches / halfs`

Change this to `3` (Valve's Casual and Competitive default value).

Problem solved, you're welcome ;)

**Comment by Raphiy** [comment]
Perfect!! Thank you very much!! :D

**Comment by hifull** [comment]
> I know this issue, and it's related to ESL's `esl5on5.cfg`. This is the problematic line:
> `mp_win_panel_display_time 15 // The amount of time to show the win panel between matches / halfs`
> 
> Change this to `3` (Valve's Casual and Competitive default value).
> 
> Problem solved, you're welcome ;)

Thank you, a kind man! U have resolved a tournament pain <3

**Comment by MiguelNdeCarvalho** [comment]
Thanks you saved me too! 😁
