### ISSUE TITLE
Possibility to see who votes for which maps

### ISSUE THREAD

**Issue by niekcandaele** [splewis/csgo-pug-setup#273]
Would it be possible to have a vote summary after the voting? Public or in console would be nice.

**Comment by splewis** [comment]
Votes are already printed to console when sm_pugsetup_instant_runoff_voting is enabled (it is by default).

**Comment by niekcandaele** [comment]
Hmm really? I had that enabled and checked console last time we played a match. There was some dispute about the map so I wanted to verify who voted what. It's not in the logs.

In any case, I just saw [this](https://github.com/splewis/csgo-pug-setup/blob/master/scripting/pugsetup/mapvote.sp#L49) which will fit my use case well enough.

Good to close this issue if you want, thanks for the info! ;)
