### ISSUE TITLE
Bypassing .ready as an admin?

### ISSUE THREAD

**Issue by OddFodd** [splewis/csgo-pug-setup#275]
Hi,

Thanks for this wonderful plugin I like it more than the other alternatives, however since we play gathers most of the time, it's kind annoying to keep telling them to .ready. Is there a way to bypass the need for all players to ready up? And manually start the game as an admin instead?

**Comment by Technoblazed** [comment]
.forcestart will start the next stage.

**Comment by OddFodd** [comment]
oh thanks!

**Comment by borzaka** [comment]
Also there is a `.forceready` command.
