### ISSUE TITLE
Wrong map voting results for the 2nd and 3rd place

### ISSUE THREAD

**Issue by borzaka** [splewis/csgo-pug-setup#276]
### Expected behavior
The voting system records and displays the real voting results for the 1st, 2nd and the 3rd place.

### Actual behavior
I tested the voting system alone, because some odd results came up when we played together and voted for a map to play on.

So, I hope these pictures can help to see that something is not quite right;
- I never voted to de_train, but it came up 2nd place
- I never voted to de_overpass, but it came up 3rd place

![image](https://user-images.githubusercontent.com/1230402/54483369-32e69080-4852-11e9-8773-8ced9ca4be63.png)

![image](https://user-images.githubusercontent.com/1230402/54483372-485bba80-4852-11e9-851e-3f1d9a8fa680.png)

It was always de_train and de_overpass the 2nd and 3rd place winners in this cases, but I never picked either of them.

### Steps to reproduce
1. setup a pug with 'vote for a map' Map type
2. start voting, and check the results

`sm_pugsetup_instant_runoff_voting` is `1` in the config.

- Plugin version: "CS:GO PugSetup" (2.0.5) by splewis
- Sourcemod version: SourceMod 1.9.0.6260, by AlliedModders LLC

**Comment by splewis** [comment]
This is just a consequence that the algorithm is basically rounds of 'find the least voted map'. If there's only a single voter, then 6 of the 7 maps tie for that, and get eliminated in an undefined order. 

I suppose it's a bug, but in practice with 10 voters the odds of this actually changing what is printed out as 2nd and 3rd is extremely unlikely (they'd basically all have to vote in unison). For that reason I don't think this is worth fixing.

**Comment by splewis** [comment]
There is also debug logging (sm_pugsetup_debug) that you can output that would show the way everyone voted and what happened each round of the algorithm.

If you think there is a "real bug" and can get that info - feel free to reopen with it. Otherwise I don't think there's a problem here, I've observed the runoff voting working hundreds of times as expected.
