### ISSUE TITLE
Update Translation Portuguese-BR

### ISSUE THREAD

**Issue by paulocrash** [splewis/csgo-pug-setup#279]
I updated the translation `pt`, if it can put in the next update it would be perfect.

I have updated based on the latest standard language en available in download releases, [version 2.0.5](https://github.com/splewis/csgo-pug-setup/releases/tag/2.0.5).

Attached is the translation: 
[pugsetup.phrases.txt](https://github.com/splewis/csgo-pug-setup/files/3027376/pugsetup.phrases.txt)

**Comment by b3none** [comment]
Create a pull request with the changes... or... If you'd like I can do this on your behalf?

**Comment by paulocrash** [comment]
[quote]or... If you'd like I can do this on your behalf?[/quote]
It would be perfect, I have no idea how to do it. :(

**Comment by b3none** [comment]
Please make sure the translation file is in this format:
https://github.com/splewis/csgo-pug-setup/blob/master/translations/pt/pugsetup.phrases.txt

**Comment by paulocrash** [comment]
I was able to pull Pull: https://github.com/splewis/csgo-pug-setup/pull/289
