### ISSUE TITLE
!forceunpause / pause timer

### ISSUE THREAD

**Issue by akelahvh** [splewis/csgo-pug-setup#280]
Hey I would like if there is a chance of geting pause timer 3min/half or command !forceunpause becausec the enemy team often doesn't wants to unpause after 3 minutes and that's really annoying

**Comment by akelahvh** [comment]
and I can't get "get5" to work and I have been trying for a long time now

**Comment by splewis** [comment]
I don't plan on adding any such pausing features to pugsetup. It's meant for private 10mans/gathers.

You can always disable pausing or ``rcon mp_unpause_match``. 

> and I can't get "get5" to work and I have been trying for a long time now

Okay. There's a [get5 issues section](https://github.com/splewis/get5/issues).
