### ISSUE TITLE
how to do automatic demos ? (pugsetup)_

### ISSUE THREAD

**Issue by eelade1** [splewis/csgo-pug-setup#283]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior

how do i get auto demos ? 

### Steps to reproduce

Please note that "latest" is NOT a version! Run "sm plugins" in console to find out the exact plugin version.

- Plugin version:
- Sourcemod version:
- Steps to reproduce (please be specific):

**Comment by borzaka** [comment]
First, you need to [enable gotv](https://github.com/splewis/csgo-pug-setup#enabling-gotv) to use the built-in demo-recording feature.

And than you can enabledemo  recording in the `!setup`, or set this to default `1` in `setupoptions.cfg`

**Comment by WardPearce** [comment]
Might be worth checking out https://github.com/WardPearce/SQLMatches
