### ISSUE TITLE
Doubt with Forceend and Warmup

### ISSUE THREAD

**Issue by paulocrash** [splewis/csgo-pug-setup#287]
Using the `.forceend` command, it ends the game, but does not return to the warmup, have some command, besides the `.setup` menu that can be used directly in the chat? Or just by the `.setup` itself?

I believe it is related to issues #246.

**Comment by splewis** [comment]
I don't understand what your question is. 

If you're asking 'is there a command to execute warmup configs?' then no.

**Comment by paulocrash** [comment]
Is this, any command that runs the warmup after someone uses `.forceend`, would it be possible to put in future updates?

So if someone uses the `.forceend` command we can use the `.warmup` command to restart the game completely, leaving everyone marked NotReady again.

**Comment by borzaka** [comment]
@paulocrash If you use `.forceend`, you have to setup your match again by typing `.setup` and press `1` (Finish setup).

**Comment by paulocrash** [comment]
> @paulocrash If you use `.forceend`, you have to setup your match again by typing `.setup` and press `1` (Finish setup).

Yes, I understood... I thought I could include in future updates some command so that when using `.forceend`, using the command, for example, `.warmup` it would already execute automatically instead of doing the whole process of `.setup` and press `1` **_(Finish setup)_**.

Anyway, thank you anyway.
