### ISSUE TITLE
Demo's No Longer Saving After "sm_pugsetup_demo_name_format" Change (even default value no longer works)

### ISSUE THREAD

**Issue by shayota** [splewis/csgo-pug-setup#288]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior
For Demos to record and save into csgo folder after enabling the tv commands and enabling it in pug setup.

### Actual behavior
The demos are not saving to the csgo folder or any folder.

### Steps to reproduce
When I first added the tv commands to my server.cfg it saved the demos no problem. The problem started to occur when I attempted to change the cvar: sm_pugsetup_demo_name_format "pug_{MAP}_{TIME}"

I changed the cvar to: sm_pugsetup_demo_name_format "demos/pug_{MAP}_{TIME}"
in attempt to get the demos to automatically save to a folder named "demos" inside the csgo folder.

Now the demos wont save even when I've changed the cvar back to its default.

I've been reading that it could be a permissions issue, if this was the problem would I want to give the csgo folder a 777 permission setting?

If any log files are needed I can easily post them :)

---------------------------------------------------------------------------------------------------
Plugin Versions:
"CS:GO PugSetup" (2.0.5) by splewis
SourceMod 1.9.0.6276, by AlliedModders LLC

**Comment by shayota** [comment]
I will be closing this short lived thread due to finding the solution.

It was just a permissions issue and giving the csgo folder 777 made it so the demos saved again.

However the demo pathing is still a WIP but my main issue has been solved

**Comment by splewis** [comment]
All pugsetup does is issue a `tv_record` command to the server with whatever name the pattern you gave it is.

If `tv_record` doesn't accept subdirectories, that's a change you have to take up with Valve. AFAIK, though, it should work if the directory exists.
