### ISSUE TITLE
Doubt with Map Voting Options

### ISSUE THREAD

**Issue by paulocrash** [splewis/csgo-pug-setup#290]
I would like to know if I could do the voting options of PUGSetup at the end of the competitive, currently has `vote`, `veto` and `current`.

I did the test with the voting options, but the voting appears at the beginning of the competition, when everyone types `.ready`, would have some way to make the vote appear at the end of the competition, when it is missing X round to finish would open the menu map voting.

**Comment by splewis** [comment]
I don't intend to allow such a change. It doesn't seem worthwhile for the complication it would add.
