### ISSUE TITLE
Problems with map switching & map voting

### ISSUE THREAD

**Issue by paulocrash** [splewis/csgo-pug-setup#291]
### Expected behavior
When I use the option to use current map instead of mapping the PUGSetup plugin, and using SourceMod's default map voting plugin, MapChooser, which at the end of the competitive map poll the server should switch to the map chosen in the vote.

### Actual behavior
When you activate the option to use current map in PUGSetup, and activate the default MapMooser plugin of SourceMod to do the map voting at the end of the round, the voting until rolls, players vote on the map and until then everything is alright, but at the time of exchanging the server does not exchange, it gives a reload to the same map.

I saw that when the PUGSetup plugin is active and I use this map voting option the nextmap.smx plugin simply does not work, the bug in the nextmap.smx plugin.

### Steps to reproduce
**- Plugin Version:**
```
  30 "CS:GO PugSetup" (2.0.5) by splewis
  31 "CS:GO PugSetup: RWS balancer" (2.0.5) by splewis
  32 "CS:GO PugSetup: team locker" (2.0.5) by splewis
  33 "CS:GO PugSetup: autokicker" (2.0.5) by splewis
  34 "CS:GO PugSetup: team names setter" (2.0.5) by splewis
  35 "CS:GO PugSetup: damage printer" (2.0.5) by splewis
  36 "CS:GO PugSetup: write team money to chat" (2.0.5) by Versatile_BFG/jkroepke
  37 "CS:GO PugSetup: hostname setter" (2.0.5) by splewis
```
**- SourceMod Version:**
```
    SourceMod Version: 1.9.0.6280
    SourcePawn Engine: 1.9.0.6280, jit-x86 (build 1.9.0.6280)
    SourcePawn API: v1 = 4, v2 = 12
    Compiled on: May  1 2019 15:46:03
    Built from: https://github.com/alliedmodders/sourcemod/commit/c2d4643
    Build ID: 6280:c2d4643
    http://www.sourcemod.net/
```
**- Steps to Reproduce (please be specific):**
- Install PUGSetup on the server;
- Configure PUGSetup to use the current map for competitive;
- Activate the mapchooser.smx plugin to vote at the end of the map;
- Play the competition, at the end when there is a vote only vote and you will see that the map will not change at the end;

**_Note, I noticed that there are moments that neither makes the vote, the plugin mapchooser of the error too, since it does not find the list of maps._**

I made up a post in AlliedModders about this thinking that it would be a problem with some configuration of mine on the server or with the plugin nextmap or even the mapchooser, there are even more steps I did to see if I could fix it and how I came to the conclusion that BUG only happens when the PUGSetup Plugin is active, because when I turned it off it worked fine, both map switching and map voting.

Post Link: https://forums.alliedmods.net/showthread.php?p=2652036#post2652036

**Comment by paulocrash** [comment]
Update, I tested with the WarMod plugin, with it funciounou everything correctly, changed the map to the vote chosen by mapchooser.

**Comment by splewis** [comment]
I'm very skeptical pugsetup has anything to do with this.

It's more likely cvars being executed are the problem (e.g what's in your warmup and/or live config).

Either way - combining mapchooser & pugsetup isn't really an important use case to me, so you're probably on your own trying to fix your problem.

**Comment by paulocrash** [comment]
> I'm very skeptical pugsetup has anything to do with this.
> 
> It's more likely cvars being executed are the problem (e.g what's in your warmup and/or live config).
> 
> Either way - combining mapchooser & pugsetup isn't really an important use case to me, so you're probably on your own trying to fix your problem.

So the config I use in warmup and/or live are these, but I have not made changes to them.

Here is the `live.cfg` config:
```
ammo_grenade_limit_default 1
ammo_grenade_limit_flashbang 2
ammo_grenade_limit_total 4
bot_quota 0
mp_afterroundmoney 0
mp_autokick 0
mp_autoteambalance 0
mp_buytime 15
mp_c4timer 40
mp_death_drop_gun 1
mp_endmatch_votenextmap 0
mp_freezetime 15
mp_friendlyfire 0
mp_halftime_pausetimer 0
mp_ignore_round_win_conditions 0
mp_limitteams 0
mp_match_end_restart 1
mp_match_restart_delay 30
mp_maxmoney 16000
mp_maxrounds 30
mp_overtime_enable 1
mp_overtime_halftime_pausetimer 0
mp_overtime_maxrounds 6
mp_overtime_startmoney 10000
mp_respawn_immunitytime 0
mp_respawn_on_death_ct 0
mp_respawn_on_death_t 0
mp_round_restart_delay 5
mp_roundtime 1.92
mp_roundtime_defuse 1.92
mp_roundtime_hostage 1.92
mp_startmoney 800
mp_timelimit 0
mp_weapons_allow_typecount 5
spec_freeze_deathanim_time 0
spec_freeze_panel_extended_time 0
spec_freeze_time 2
spec_freeze_time_lock 2
spec_replay_enable 0
sv_allow_votes 0
sv_auto_full_alltalk_during_warmup_half_end 1
sv_competitive_official_5v5 1
sv_deadtalk 1
sv_talk_enemy_dead 0
sv_talk_enemy_living 0
sv_voiceenable 1
```
Here is the `warmup.cfg` config:
```
bot_quota 0
mp_afterroundmoney 16000
mp_autokick 0
mp_autoteambalance 0
mp_buytime 6000
mp_death_drop_gun 0
mp_free_armor 2
mp_freezetime 1
mp_friendlyfire 0
mp_maxrounds 30
mp_respawn_immunitytime 2
mp_respawn_on_death_ct 1
mp_respawn_on_death_t 1
mp_round_restart_delay 3
mp_roundtime 1.75
mp_roundtime_defuse 1.75
mp_roundtime_hostage 1.75
mp_solid_teammates 0
mp_spectators_max 20
mp_startmoney 16000
mp_timelimit 0
sv_alltalk 1
sv_auto_full_alltalk_during_warmup_half_end 1
sv_competitive_official_5v5 1
sv_full_alltalk 1
ammo_grenade_limit_default 0
ammo_grenade_limit_flashbang 0
ammo_grenade_limit_total 0
```
About using mapchooser & pugsetup together is that I prefer map voting at the end of the competitive, in any case I'll be seeing a little more to see where the problem is, but honestly I no longer know where to look.
