### ISSUE TITLE
demo naming

### ISSUE THREAD

**Issue by adamheath** [splewis/csgo-pug-setup#292]
I am running multiple csgo server instances off the same base files, each have their own unique start file and server.cfg but all using the same pug mod configs. 

Is it possible to make sure each demo has a unique name? I'm worried about multiple games started at the same time on the same map and so are named the same thing.

Failing that, would it be possible for each instance to have its own folder where demos are stored?

**Comment by splewis** [comment]
You can set the sm_pugsetup_demo_name_format and sm_pugsetup_time_format cvars to whatever you like. 

You can put a directory in the name format, but you probably need to make sure the directory already exists.
