### ISSUE TITLE
No bomb on T team & teammates not showing on radar

### ISSUE THREAD

**Issue by stelz0r** [splewis/csgo-pug-setup#293]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior
Well someone on the T team should have a bomb.

### Actual behavior
No one has got the bomb and teammates are not showing on the radar + names of them are showing up in red when aiming at them like if they're enemies.

### Steps to reproduce

Please note that "latest" is NOT a version! Run "sm plugins" in console to find out the exact plugin version.

- Plugin version: PugSetup 2.0.5 | Practicemode 1.3.3
- Sourcemod version:1.9.0.6281
- Steps to reproduce (please be specific):
sadly i can't reproduce this. sometimes it happens, sometimes everything works fine. sometimes i restart my server 3 times and it happens everytime...

**Comment by splewis** [comment]
> No one has got the bomb and teammates are not showing on the radar + names of them are showing up in red when aiming at them like if they're enemies.

Sounds like you set
```
mp_give_player_c4 0
mp_teammates_are_enemies 1
```
somewhere.

You can remove any other plugins & restore the warmup/live configs to their defaults to debug it.

**Comment by splewis** [comment]
Feel free to reopen if you have more issues, but there's no evidence of a pugsetup issue here yet.
