### ISSUE TITLE
Votemap at the end of map/match.

### ISSUE THREAD

**Issue by SanjaySRocks** [splewis/csgo-pug-setup#295]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior
Votemap at the end of win scoreboard after pug complete.

### Actual behavior
Votemap ddont work at the end of pug.

### Steps to reproduce
Simple Pug Install.

Please note that "latest" is NOT a version! Run "sm plugins" in console to find out the exact plugin version.

- Plugin version: 21 "CS:GO PugSetup" (2.0.5) by splewis
- Sourcemod version:

SourceMod Version Information:
SourceMod Version: 1.9.0.6281
SourcePawn Engine: 1.9.0.6281, jit-x86 (build 1.9.0.6281)
SourcePawn API: v1 = 4, v2 = 12
Compiled on: May 14 2019 16:03:05
Built from: https://github.com/alliedmodders/sourcemod/commit/c5efe48
Build ID: 6281:c5efe48
http://www.sourcemod.net/

- Steps to reproduce (please be specific):

**Comment by paulocrash** [comment]
As I understand it, you want the vote at the end of the map, that is, when the competitive / mix is ​​ending.

I tried to use SourceMod's own vote, but to no avail, as you can see here: #291

I also find it interesting if I had a map voting option at the end of the game, but I have already requested this and the author does not intend to make this change: #290

Anyway, I hope you're luckier than me and that he changed his mind.

**Comment by splewis** [comment]
I have no plans for Pugsetup to integrate with CS:GO's builtin map voting mechanism.

If there is a specific pull request for a feature, we can discuss it, but otherwise pugsetup works as intended and does not interact with the builtin voting mechanisms for CS:GO or sourcemod.
