### ISSUE TITLE
How to remove the pause automatically?

### ISSUE THREAD

**Issue by dwwesley** [splewis/csgo-pug-setup#300]
Dear, all good with you?

I am using the plugin on my server: [CS: GO] Pug Setup (v2.0.5, 2018-08-05)

The plugin works perfectly, but I just missed one function, I wish the configuration file had some CVAR, with the time needed for a break, for example, that I put both teams could pause only 2x by half, and each break should have a time of 60 seconds.

What happens today is that someone needs to write the command to remove the pause from the game.

**Comment by splewis** [comment]
I don't plan to add timed pauses to pugsetup,  [get5](https://github.com/splewis/get5) is a plugin designed for matches with competition style rules like this, pugsetup is intended for "friends only" style games.

You can force unpause via ``rcon mp_unpause_match``, as a fallback.
