### ISSUE TITLE
Hearcoach plugin with PugSetup?

### ISSUE THREAD

**Issue by Enghausen-petabit-gg** [splewis/csgo-pug-setup#307]
Hi,

Great work on PugSetup! In our E-sport community we are using the Coach function and we tested out the "Hearcoach plugin" from the sm-misc repo. Does this plugin only work with Get5? We testet it out on PugSetup but we only got coach voice in timeouts.

The Coachcommand (Build 19) plugin works great with PugSetup.

- Plugin version (pugsetup): 2.0.6-dev+489
- Plugin version (Coach deadtalk fix): Build 19
- Sourcemod version:  1.9.0.6282

**Comment by splewis** [comment]
I see no reason why it wouldn't work. You might have other plugins interfering with it.

**Comment by Enghausen-petabit-gg** [comment]
Hi,

Only got these plugins active on the server.

```
sm plugins list
[SM] Listing 8 plugins:
  01 "Admin Help" (1.9.0.6282) by AlliedModders LLC
  02 "Basic Commands" (1.9.0.6282) by AlliedModders LLC
  03 "Basic Ban Commands" (1.9.0.6282) by AlliedModders LLC
  04 "CS:GO PugSetup: damage printer" (2.0.6-dev+489) by splewis
  05 "CS:GO PugSetup" (2.0.6-dev+489) by splewis
  06 "Admin File Reader" (1.9.0.6282) by AlliedModders LLC
  07 "Admin Menu" (1.9.0.6282) by AlliedModders LLC
  08 "Coach command" (Build 19) by splewis
```
I removed the "Coach deadtalk fix" plugin because it was not working. We tested it in 10 matches with no luck and ending up using Team Speak and Discord. 

Are we 100% sure the plugin still works? Thinking it's a "bypass" on Valve changing thinks and a update could have broken it?

**Comment by splewis** [comment]
> Are we 100% sure the plugin still works? 

I haven't used the plugin since I wrote it years ago, so I have no idea if it should still work. Afaik, people still use it, though.
