### ISSUE TITLE
Doesnt detect / work

### ISSUE THREAD

**Issue by coolmelon69** [splewis/csgo-pug-setup#310]
Hello so i already installed it as the manual said and but it my server doesnt detect the plugin. How can i fix this?

**Comment by splewis** [comment]
It's hard to help without any more information. The [sourcemod forums](https://forums.alliedmods.net/forumdisplay.php?f=58) may be a better place to get help. You should probably start by checking your:
- metamod:source installation (does `meta version` in console work?)
- sourcemod installation (does `sm version` in console work?)
- does the plugin load at all? (does it show up in the `sm plugins` output in console)
