### ISSUE TITLE
Add wingman option

### ISSUE THREAD

**Issue by ctrlvv** [splewis/csgo-pug-setup#311]
Add wingman option to the .setup menu (change server to game_mode 2

Would be awesome when people wants to play 2on2.

**Comment by splewis** [comment]
I don't plan on adding this to pugsetup. 

It's possible to add your own functionality for the .setup menu through another plugin, though: https://github.com/splewis/csgo-pug-setup/blob/master/scripting/include/pugsetup.inc#L50-L65
