### ISSUE TITLE
where is the .smx file?

### ISSUE THREAD

**Issue by suntay44** [splewis/csgo-pug-setup#313]
![image](https://user-images.githubusercontent.com/25594138/74899785-d207f680-53d8-11ea-99a2-4afac68ad3d5.png)

**Comment by splewis** [comment]
With the release downloads: https://github.com/splewis/csgo-pug-setup/releases

I don't check compiled binaries into the source tree.

**Comment by suntay44** [comment]
so i will download both right (sourcecode & pugsetup_2.0.5) ? and overright the other files? or I will just get the .smx from the other zip

**Comment by suntay44** [comment]
![image](https://user-images.githubusercontent.com/25594138/74900447-c9b0bb00-53da-11ea-9c87-3ede659a36b9.png)

which is which to be unzip in the server

**Comment by splewis** [comment]
pugsetup_2.0.5.zip

**Comment by suntay44** [comment]
is it the same with get5
