### ISSUE TITLE
Friendly Fire

### ISSUE THREAD

**Issue by bNg91** [splewis/csgo-pug-setup#317]
good morning, i would like to know if there is any way to configure the live.cfg file to remove the friendly fire but keep the damage from molotov, incendiary and HE.

**Comment by splewis** [comment]
You can put whatever cvars you like in live.cfg, but I don't know what cvars you specifically want. Probably some of these: 

> mp_friendlyfire 
ff_damage_reduction_bullets
ff_damage_reduction_grenade
ff_damage_reduction_grenade_self
ff_damage_reduction_other 

But these aren't related to pugsetup, just cvars built into the game.
