### ISSUE TITLE
missing file

### ISSUE THREAD

**Issue by daeseong** [splewis/csgo-pug-setup#320]
### Expected behavior

According to "Configuration" step: After installing the plugin, start the server and check cfg/sourcemod/pugsetup. There will be a file called **_pugsetup.cfg_** that you can edit to change the cvars the plugin uses. I recommend skimming this file at least to see if there's anything you want to change.

### Actual behavior

**_pugsetup.cfg_** is missing and .setup isn't working.

### Steps to reproduce

Please note that "latest" is NOT a version! Run "sm plugins" in console to find out the exact plugin version.

- Plugin version: 1.10
- Sourcemod version: 1.10
- Steps to reproduce (please be specific): Followed the steps in README exactly.

**Comment by splewis** [comment]
Check your error logs in ``addons/sourcemod/logs``.

You can check if the plugin is running at all using the ``sm plugins`` command as well.

**Comment by debdutgoswami** [comment]
+1 I am facing the same issue. I downloaded the latest build as well as the lates build for sourcemod and metamod. My sourcemode admin plugin is working fine but it is missing `pugsetup.cfg` so the in-game commands are not working.

**Comment by splewis** [comment]
> but it is missing pugsetup.cfg so the in-game commands are not working.

That doesn't follow. The file isn't required. It's just default cvars when created at first.

Like I said before: Check your error logs in addons/sourcemod/logs.
