### ISSUE TITLE
pugsetup_teamnames: Apply Logos & Names of professional teams automatically when starting competitive

### ISSUE THREAD

**Issue by crashzk** [splewis/csgo-pug-setup#321]
Apply Logos & Names of professional teams automatically when starting competitive, something similar that WarMod [BFG] has.

Logos and team names could be taken here: https://web.archive.org/web/20161119205930/http://csgo-data.com/in-game.php

How it would work, when all players typed `sm_ready`, when the mix / competitive will actually start, the plugin would choose a random team for both teams.

It would also be interesting if, together with logos and team names, automatically applied the team's TAG to the players.

**Comment by splewis** [comment]
I'm not going to add this, it's not worth the extra code. The module system is setup for users to add their own behavior like this (`pugsetup_teamnames` is more of an example really).
