### ISSUE TITLE
Automatic select captains

### ISSUE THREAD

**Issue by w0www** [splewis/csgo-pug-setup#323]
Hello, first of all, congrats because this plugins is AWESOME! easy and fast! :D

Now, we want do this more automatic.. when all players type .ready, one of each team have to select as captain automatic, would be awesome.

after this, they can veto maps and start play! :D 

if this not is possible, can we select captains from admin console?

**Comment by MoritzLoewenstein** [comment]
You can set `sm_pugsetup_auto_randomize_captains 1` to automatically choose 1 random captain in each team.

**Comment by splewis** [comment]
Yes, you can already do this.

**Comment by w0www** [comment]
thanks guys
