### ISSUE TITLE
Detect player who abandons/leave a live match

### ISSUE THREAD

**Issue by Ishaan-Kumar** [splewis/csgo-pug-setup#325]
Is there any way by which we can get a list of players who leave the server in between match i.e who abandons?

Will give them bans automatically or anything like that?

**Comment by MikkelDK** [comment]
You need a custom plugin for that. =) https://forums.alliedmods.net/showthread.php?t=319581 e.g

**Comment by Ishaan-Kumar** [comment]
Thanks. Closing issue :)
