### ISSUE TITLE
Please help me about warm-up and BOT features

### ISSUE THREAD

**Issue by soscaster** [splewis/csgo-pug-setup#327]
I want to reset the game to the unlimited warm-up, and add bot to the warm-up (after the real player join the bot will be kicked). How can I do it right on this project ?
And I want to automatic choose my Steam account as the admin. If you can make it, I will be very happy !
I think these features it's necessary, so if you can, please help me.

**Comment by splewis** [comment]
> I want to reset the game to the unlimited warm-up, and add bot to the warm-up (after the real player join the bot will be kicked). How can I do it right on this project ?

You can put whatever cvaras you want in the warmup config: sourcemod/pugsetup/warmup.cfg

> And I want to automatic choose my Steam account as the admin. If you can make it, I will be very happy !

Not sure what "the admin" means in this context. Sourcemod admin? "Pug leader"? Both? You can make yourself sourcemod admin and issue whatever commands you want.

**Comment by soscaster** [comment]
> Not sure what "the admin" means in this context. Sourcemod admin? "Pug leader"? Both? You can make yourself sourcemod admin and issue whatever commands you want.

I mean the only one can control the menu and the match

**Comment by Ishaan-Kumar** [comment]
Have a look at
[https://github.com/splewis/csgo-pug-setup/blob/master/configs/pugsetup/permissions.cfg](url)

Edit "all" of the commands to "admin" for which you want only admin can use.

"admin" means players who have flag "b" in sourcemod 

And add yourself to the admin list in sourcemod

[https://wiki.alliedmods.net/Adding_Admins_(SourceMod)](url)
