### ISSUE TITLE
My server not going public

### ISSUE THREAD

**Issue by xXDarkLordXx1234** [splewis/csgo-pug-setup#332]
I want to make my server for public but whenever my friends try to join the ip they cant, pls help me in this regard

**Comment by Ishaan-Kumar** [comment]
Lol, nobody will reply and cant help you without any help of logs or config. You need to learn first how to get help with coding. It's not like pls help me. 

Instead you should try, these are my configs. I have tried this and this but didn't succeed. May be the problem is this.

**Comment by splewis** [comment]
Try the sourcemod forums for general help: https://forums.alliedmods.net/forumdisplay.php?f=130
