### ISSUE TITLE
Errors on sm_forceready from invalid permissions

### ISSUE THREAD

**Issue by ccsimplyspolit** [splewis/csgo-pug-setup#336]
Please note that "latest" is NOT a version! Run "sm plugins" in console to find out the exact plugin version.

- Plugin version:  "CS:GO PugSetup" (2.0.6-dev) by splewis
- Sourcemod version:SourceMod 1.10.0.6484, by AlliedModders LLC
- Steps to reproduce (please be specific):
1. Create team without captains
2. set perms to sm_forceready captains
3. Got error when type sm_forceready player
![image](https://user-images.githubusercontent.com/29892758/80838414-a63b9500-8c01-11ea-97af-63b23fae90bf.png)

L 05/01/2020 - 19:59:06: [SM] Exception reported: Unknown permission value: 1
L 05/01/2020 - 19:59:06: [SM] Blaming: pugsetup.smx
L 05/01/2020 - 19:59:06: [SM] Call stack trace:
L 05/01/2020 - 19:59:06: [SM]   [0] ThrowNativeError
L 05/01/2020 - 19:59:06: [SM]   [1] Line 407, pugsetup/natives.sp::Native_HasPermissions
L 05/01/2020 - 19:59:06: [SM]   [3] PugSetup_HasPermissions
L 05/01/2020 - 19:59:06: [SM]   [4] Line 758, D:\pl\sourcemod-1.11.0-git6522-windows\addons\sourcemod\scripting\pugsetup.sp::DoPermissionCheck
L 05/01/2020 - 19:59:06: [SM]   [5] Line 1212, D:\pl\sourcemod-1.11.0-git6522-windows\addons\sourcemod\scripting\pugsetup.sp::Command_ForceReady
L 05/01/2020 - 19:59:06: [SM]   [7] FakeClientCommand
L 05/01/2020 - 19:59:06: [SM]   [8] Line 1066, D:\pl\sourcemod-1.11.0-git6522-windows\addons\sourcemod\scripting\pugsetup.sp::CheckChatAlias
L 05/01/2020 - 19:59:06: [SM]   [9] Line 1094, D:\pl\sourcemod-1.11.0-git6522-windows\addons\sourcemod\scripting\pugsetup.sp::OnClientSayCommand_Post
Rat1nov: sm_forceready
L 05/01/2020 - 19:59:13: "Rat1nov<171><STEAM_1:0:50404326><TERRORIST>" say "sm_forceready"
L 05/01/2020 - 19:59:14: [SM] Exception reported: Unknown permission value: 1
L 05/01/2020 - 19:59:14: [SM] Blaming: pugsetup.smx
L 05/01/2020 - 19:59:14: [SM] Call stack trace:
L 05/01/2020 - 19:59:14: [SM]   [0] ThrowNativeError
L 05/01/2020 - 19:59:14: [SM]   [1] Line 407, pugsetup/natives.sp::Native_HasPermissions
L 05/01/2020 - 19:59:14: [SM]   [3] PugSetup_HasPermissions
L 05/01/2020 - 19:59:14: [SM]   [4] Line 758, D:\pl\sourcemod-1.11.0-git6522-windows\addons\sourcemod\scripting\pugsetup.sp::DoPermissionCheck
L 05/01/2020 - 19:59:14: [SM]   [5] Line 1212, D:\pl\sourcemod-1.11.0-git6522-windows\addons\sourcemod\scripting\pugsetup.sp::Command_ForceReady

**Comment by splewis** [comment]
https://github.com/splewis/csgo-pug-setup/commit/38537fed753f1128bd2f35abce5ca1ff8d6b7223 should have fixed this.
