### ISSUE TITLE
Trying to save demos

### ISSUE THREAD

**Issue by ExxonYT** [splewis/csgo-pug-setup#339]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior
I thought the demos would automatically save for each Pug/Scrim we do.

### Actual behavior
One of the demo's it saved the hour and a half practice session we did beforehand as well as the scrim meaning we now cannot send the other team the demo due to it having us going through all our strats and weird smokes that we created line ups for. It also then didn't save the demo from the next scrim we did which was only 15 mins later. Please explain how it knows when the Pug starts, I expected once I click finish setup (to start the game) it should start recording the demo and finish once the match finishes. Also, the demos are just saving in general not in an actual folder.

### Steps to reproduce

Please note that "latest" is NOT a version! Run "sm plugins" in console to find out the exact plugin version.

- Plugin version:
- Sourcemod version:
- Steps to reproduce (please be specific):

**Comment by splewis** [comment]
Pugsetup issues a `tv_record` console command when the game is going live
(when all 10 players ready up), and then issues a `tv_stoprecord` command
after the match finishes.

The code that does it:
https://github.com/splewis/csgo-pug-setup/blob/d50024b9a1ec53f8783e947b539ab2f8208254c3/scripting/pugsetup.sp#L1819-L1822
https://github.com/splewis/csgo-pug-setup/blob/8a6995e7404bceda5aa1f8fd44ccd2984fbf6de0/scripting/pugsetup/util.sp#L211-L237

Note that you need both:
- GOTV to be enabled (tv_enable 1 in your server.cfg typically)
- Demo recording to be enabled in the pug's setup options. The default is
**disabled**:
https://github.com/splewis/csgo-pug-setup/blob/master/configs/pugsetup/setupoptions.cfg#L35

> Also, the demos are just saving in general not in an actual folder.

That's how the base CSGO server works. Pugsetup doesn't do anything beyond
issuing those 2 commands for recording demos.

I can't explain what you saw with the demo timings appearing strange. Any
other user/plugin could also be issuing tv_record/tv_stoprecord commands as
well, so I can't really say what happened in your case. Your issue
definitely sounds out-of-line with how pugsetup typically works though.

**Comment by ExxonYT** [comment]
Hi, I am not sure then. If it keeps doing this am I able to issue the commands myself? For example I turn of record demo and use the console and put in tv_record and then tv_stoprecord? I use practicemode as well but that is the only other plugin I use. My server is a private server for scrimming and team practice.

Kind Regards,
Tom Fagan

**Comment by splewis** [comment]
Yup, you could just turn off the demo recording (from pugsetup's point of
view) and issue the commands yourself in the console. Pugsetup doesn't do
anything fancy beyond just issuing those commands.

I'd suggest trying this first though:
- Before readying up (e.g. when at 9/10 ready), check tv_status in console
(via rcon). This will tell you if the server is already recording (you'll
see a line like 'Recording to "xxx.dem", length 00:01' if it is).
- Let the game start, check tv_status after the knife/warmup, if it's not
recording then manually start it yourself (rcon tv_record filenamehere)
- Wait a few minutes after the game, check 'rcon tv_status' again, do 'rcon
tv_stoprecord if you need to.

That might help you figure out what's going on. IIRC, 'tv_status' from a
client console does not reveal all information. So it's important to use
the server console for the command (e.g. use rcon if you're issuing the
commands ingame).

**Comment by ExxonYT** [comment]
Perfect thank you, I think this will work better since I can choose the file name of it as well 

Kind Regards,
Tom Fagan
