### ISSUE TITLE
Custom knife.cfg

### ISSUE THREAD

**Issue by Ishaan-Kumar** [splewis/csgo-pug-setup#340]
Just like warmup.cfg and live.cfg have custom cvars to set. We need custom knife.cfg cvar

**Comment by splewis** [comment]
Just added. The reason it didn't exist before was that the knife round
handling is a bit different from the other configs. The knife round
executes the config, but also saves & restores the cvars values before the
knife round once the knife round is complete. (The intention is to make it
easier for users to set knife round settings without having to "fix" them
back in the live config)

Regardless - the cvar (untested) is now with newer builds. Let me know if
it doesn't work.
