### ISSUE TITLE
Not reporting any error

### ISSUE THREAD

**Issue by IshaanKr** [splewis/csgo-pug-setup#344]
### Expected behavior
PugSetup should some error in this scenario.

### Steps to reproduce
As a server admin, I just want to test the server

connected to server
set captain -> Manual switch
select map -> Current Map
sm_forcestart 
Ready/Not-Ready TAGS are gone, the game still in warmup, pugsetup didn't report any error. What to expect now?

Please note that "latest" is NOT a version! Run "sm plugins" in the console to find out the exact plugin version.

- Plugin version:
- Sourcemod version:
- Steps to reproduce (please be specific):

**Comment by splewis** [comment]
I can't reproduce this issue on v2.0.7. If you believe it's still a bug, feel free to reopen & post more version information.
