### ISSUE TITLE
pugsetup_hostname not setting properly

### ISSUE THREAD

**Issue by IshaanKr** [splewis/csgo-pug-setup#345]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior
changed the hostname to what we like
hostname plugin setting LIVE/NEED with old hostname string

### Actual behavior
hostname plugin should respect the new hostname string

### Steps to reproduce
Server started with some random name
Later change the cvar hostname
Start pugsetup
hostname plugin still using the old hostname string 

Please note that "latest" is NOT a version! Run "sm plugins" in console to find out the exact plugin version.

- Plugin version:
- Sourcemod version:
- Steps to reproduce (please be specific):

**Comment by splewis** [comment]
See #394
