### ISSUE TITLE
The plugin is not working for me (new to csgo server)

### ISSUE THREAD

**Issue by Hankeei** [splewis/csgo-pug-setup#346]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior

Hello Im new to creating csgo server
I running my csgo server in ubuntu
I installed the plugin into my server and it dont create a pugsetup.cfg 
and it not working inside the server
do I forget to install anything or I need to do smt to make it work
I installed the sourcemod and meta mod and the sm_admin work
I installed some other mod and they are not working too

### Steps to reproduce
I installed the plugin by following the instruction

Please note that "latest" is NOT a version! Run "sm plugins" in console to find out the exact plugin version.

- Plugin version: pug-setup 2.0.5
- Sourcemod version: sourcemod-1.10.0-git6488-linux
- Steps to reproduce (please be specific):

**Comment by splewis** [comment]
Check your error logs. addons/sourcemod/logs
