### ISSUE TITLE
!gg for .endgame

### ISSUE THREAD

**Issue by tornike015** [splewis/csgo-pug-setup#347]
hello, i know that .endgame is surrend command but i want  change it like faceit. want !gg for .endgame, is this possible?

**Comment by splewis** [comment]
You can add custom command aliases to [configs/pugsetup/chataliases.cfg](https://github.com/splewis/csgo-pug-setup/blob/master/configs/pugsetup/chataliases.cfg) for `sm_endgame`. There is no forfeit vote command though. Only `sm_endgame`.

**Comment by tornike015** [comment]
TNX, ITS WORKING BUT, when i surrended, in new game  ready and notready not working, when i will write !setup and next finish...  its working but  i want  after surrend  !ready and unready.  please help me .

**Comment by splewis** [comment]
Can you post specific steps to reproduce, including plugin version? The default issue template asks for those for a reason, it's much more difficult to help without that information:

```
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior



### Actual behavior



### Steps to reproduce

Please note that "latest" is NOT a version! Run "sm plugins" in console to find out the exact plugin version.

- Plugin version:
- Sourcemod version:
- Steps to reproduce (please be specific):

```
