### ISSUE TITLE
Ready and heating system not enabled

### ISSUE THREAD

**Issue by dwwesley** [splewis/csgo-pug-setup#351]
Dears, good morning,

I have a little doubt.
I've already set up the file: setupoptions.cfg to my style, but I think I'm doing something wrong.

As I have already set up the "setupoptions.cfg" file, I would like that as soon as the players connect to the server, the heating will be available with the option to get ready!

However, what is happening is the opposite, there is no heating, no option to give it ready, as an administrator I need to access the .setup command and click on finish configuration, to enable the heating and ready system.

What do I have to do ? To make this enabled and automated !!!

**Comment by rugalservidores** [comment]
Hello, there is a cvar that you need to enable for this to happen.
Go to csgo / cfg / sourcemod / pugsetup / pugsetup.cfg
inside this file there is a cvar called "sm_pugsetup_autosetup" change the value from 0 to 1 and restart the server.
