### ISSUE TITLE
about the teamlocker

### ISSUE THREAD

**Issue by daoguang1012** [splewis/csgo-pug-setup#353]
hello i'm sorry to my bad english 
in my csgo server ,i use a client limiter plugins to prevent too many player entering the server (because i use a -inmaster so they must use connect command to enter my server).after all players are ready and the captains has vetoed and the server start changing maps,some new player can enter the server and the old player can't enter server because the client limiter .i use the teamlocker but it only make sense when match is live . but i want that the teams are locker as soon as the captains start veto. how can i fix it? or can you show the pugsetup_teamlocker.sp? thanks!

**Comment by splewis** [comment]
> or can you show the pugsetup_teamlocker.sp? thanks!

It's an open source plugin. https://github.com/splewis/csgo-pug-setup/blob/master/scripting/pugsetup_teamlocker.sp 

PRs welcome, if you want to change it's behavior.
