### ISSUE TITLE
sorry to ask but how do i start the server i have done every step and didnt got the uploading game sever on ftp

### ISSUE THREAD

**Issue by KrutarthChovatiya** [splewis/csgo-pug-setup#354]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Steps to reproduce

Please note that "latest" is NOT a version! Run "sm plugins" in console to find out the exact plugin version.

- Plugin version:
- Sourcemod version:
- Steps to reproduce (please be specific):

**Comment by jelondono** [comment]
You did it?

**Comment by splewis** [comment]
I'm sorry, but this isn't enough information here to help you. The sourcemod forums are probably a better place of getting basic help setting up a CS:GO server: https://forums.alliedmods.net/forumdisplay.php?f=58
