### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by rugalservidores** [splewis/csgo-pug-setup#356]
Hello, I use PugSetup 2.0.5 on my servers and it's a great plugin in the 10mans format. Anyway, I have a suggestion to be added to the plugin. It would be interesting to adjust the plugin's pause system to have a break. Example: When a team makes a pause in the match, it has a durability of 1 minute.
I think that an endless break would not be good for public servants, which is my case. (My English is terrible, sorry).

**Comment by splewis** [comment]
I don't intend to add a more sophisticated pausing system to pugsetup - it's really only intended for 'private' games. The builtin pausing system in the game might work for you, though, but I don't know all the cvars for that.
