### ISSUE TITLE
2v2 with 5 people requires everyone to type .ready

### ISSUE THREAD

**Issue by inputuserhere** [splewis/csgo-pug-setup#357]
So when I type .setup and select a 2v2 match and there are more than 4 users in the game (spectators included) it requires everyone to type .ready??

- Plugin version: Latest
- Sourcemod version: Latest
- Steps to reproduce (please be specific):

**Comment by MoritzLoewenstein** [comment]
add `sm_pugsetup_exclude_spectators 1` in `cfg/sourcemod/pugsetup.cfg`
