### ISSUE TITLE
30 ROUNDS ERROR *mp_match_can_clinch 0*

### ISSUE THREAD

**Issue by ZIODIOZIO** [splewis/csgo-pug-setup#363]
Hi, I'm trying to set up 30 game rounds with the `` mp_match_can_clinch 0 '' command in live.cfg but the matches keep ending on the 16th round win. Help please.
![Capture](https://user-images.githubusercontent.com/74601229/99388300-a9644d00-28d5-11eb-8b6c-908e0d8e97bf.PNG)

**Comment by splewis** [comment]
The "do playout' setting in the pugsetup menus/options overrides the `mp_match_can_clinch` cvar: https://github.com/splewis/csgo-pug-setup/blob/6d5077044c5fad94faa3bf03ccac3117a9591500/scripting/pugsetup.sp#L1933-L1942

The right way to change the setting would be to edit your `addons/sourcemod/configs/pugsetup/setupoptions.cfg` file here: configs/pugsetup/setupoptions.cfg

https://github.com/splewis/csgo-pug-setup/blob/6d5077044c5fad94faa3bf03ccac3117a9591500/configs/pugsetup/setupoptions.cfg#L47-L51

You could set the default to "1" to force 30-rounds, or alternatively set `display_setting` and have it show up in the `.setup` menu.
