### ISSUE TITLE
PUGDemo

### ISSUE THREAD

**Issue by maselK** [splewis/csgo-pug-setup#364]
We got PUGSetup and PraccSetup on 4 Gaming Server... with SM.

We have now following problem:

On Server 1 sometimes there is an autorecord sometimes we have an PUGDemo of a Pracc Game, but Demo is every game enabled, tv_autorecord in every cfg too.

On Server 2 and 3 we have only autorecord no PUGDemo

On Server 4 we have a lot of autorecord (always 568KB, or if there is someone then longer dmeo) and no PUG Demo) it is installed with lgsm on 1 technical server and 4 software server. We got our servers sponsored by DashHost

it would be very ncie to help us with this problem, so we have from every game a PUG Demo on every Server

best regaards Marcel 'masel_k' K.

**Comment by splewis** [comment]
I strongly suggest not using the `tv_autorecord` cvar in addition to pugsetup. That cvar will interfere with pugestup issuing any `tv_record` commands.  You definitely shouldn't use *both*.
