### ISSUE TITLE
I can't change prefix

### ISSUE THREAD

**Issue by napzeu** [splewis/csgo-pug-setup#365]
Hello, I have a problem, that I can't change prefix to our custom "UNID", there's still default one.
sm_cvar sm_pugsetup_message_prefix "[{DARK_RED}UNID{NORMAL}]",
This is what I'm posting there, then I reset server and there's still default one.
Can you please help me?

**Comment by napzeu** [comment]
I tried aswell sm_pugsetup_message_prefix "[{YELLOW}PugSetup{NORMAL}]"

**Comment by sunnus01** [comment]
Row 102 in pugsetup.cfg
// The tag applied before plugin messages. If you want no tag, you can set an empty string here.
// -
// Default: "[{YELLOW}PugSetup{NORMAL}]"
sm_pugsetup_message_prefix "[{YELLOW}WAP MIX Setup{NORMAL}]"

**Comment by splewis** [comment]
As mentioned, you edit `sm_pugsetup_message_prefix` in cfg/sourcemod/pugsetup/pugsetup.cfg.

If it's not working, check the cvar value in console.
