### ISSUE TITLE
[HELP] Enabling the "extra plugins"

### ISSUE THREAD

**Issue by ItayKisous** [splewis/csgo-pug-setup#376]
Sorry if this question has been asked before,  I'm quite new to the CSGO Servers community.

I want to know how do you enable the "extra plugins" like the damage report
Just delete it from the disabled? because I tried doing so and it didn't help me.

All answers are greatly appreciated

**Comment by spacecow123** [comment]
Move it up one folder to the plugins folder

**Comment by ItayKisous** [comment]
> Move it up one folder to the plugins folder

And after that everything should work correctly?

**Comment by ItayKisous** [comment]
> Move it up one folder to the plugins folder

I did so and it doesn't work

**Comment by sunnus01** [comment]
They should be in csgo/addons/sourcemod/plugins/ - folder

**Comment by splewis** [comment]
> I did so and it doesn't work

If so, then you should post any error logs under ``addons/sourcemod/logs``, or even the output of ``sm plugins list`` from the server console. Without those, there isn't enough information to help.
