### ISSUE TITLE
Feature Request Knife Round API

### ISSUE THREAD

**Issue by SanjaySRocks** [splewis/csgo-pug-setup#377]
Feature Request:

I just check pugsetup api i didnt find `OnKnifeRound()` or similar , could you please add it? 
Basically, i want to detect knife round and exec command on the start of knife round

I am using officially released pugsetup plugin.

**Comment by sunnus01** [comment]
You can use GameState_KnifeRound,                    // in the knife round
pugsetup.inc

**Comment by splewis** [comment]
Yes, you could do:

```
PugSetup_OnGameStateChanged(GameState before, GameState after) {
  if (after == GameState_KnifeRound) {
    // Do stuff here
  }
}
```

There's also a config file you can put commands into, that are executed on knife round: `sm_pugsetup_knife_cfg`. Default is  "sourcemod/pugsetup/knife.cfg". You can put whatever content in that file you want.
