### ISSUE TITLE
When is the next release?

### ISSUE THREAD

**Issue by Commanche2** [splewis/csgo-pug-setup#38]
When do you release the next version of the plugin? I want to test it in a server to search any spanish translation fail and correct it.

**Comment by splewis** [comment]
I'm mostly waiting for sourcemod 1.7 to be released since the plugin will requite it, which should happen sometime in the coming weeks.

**Comment by splewis** [comment]
I'm also still investigating a weird issue with players not being able to buy defuse kits from the buywheel (``buy defuser`` works in console still) after the team selection happens. I'm still perplexed to whether it's just my server, a core sourcemod issue, or a plugin issue. I haven't been able to easily reproduce it as well.

**Comment by Commanche2** [comment]
Oh! Soz. I didn't read it!! "As of 1.3.0, sourcemod 1.7 is required."

**Comment by Commanche2** [comment]
Its possible to add a knife round and a switch or stay command?

**Comment by splewis** [comment]
That got done a couple day ago: https://github.com/splewis/csgo-pug-setup/commit/6eb33f0482428c018736995e458928cff713f685

**Comment by mumixam** [comment]
@splewis i played a match last night in which someone on my team was unable to buy a kit, i think at the time i was running dev29, only 1 person was unable to buy a key from the wheel

**Comment by splewis** [comment]
I was afraid of that. I'll make a separate issue for that bug, I've seen it happen plenty of times so no screenshot should be needed - though consistently reproducing it is something I haven't been able to do.
