### ISSUE TITLE
How to let untrusted players and players who have modified files join the server

### ISSUE THREAD

**Issue by ForestNet666** [splewis/csgo-pug-setup#383]
How to let untrusted players and players who have modified files join the server
I have tried modifying server.cfg and adding startup items
sv_pure_allow_missing_files 1
sv_kick_players_with_coolddown 0

**Comment by splewis** [comment]
I can't say for sure, but it's not related to the pugsetup plugin - the [sourcemod forums](https://forums.alliedmods.net/forumdisplay.php?f=130) are a better place for this question.
