### ISSUE TITLE
All talk knife round

### ISSUE THREAD

**Issue by Siniiitchibo** [splewis/csgo-pug-setup#384]
Hi, how can I enable alltalk in knife round? I tried to edit knife.cfg file but without change. Thx for help.

**Comment by splewis** [comment]
I would suggest adding

```
sv_alltalk 1
sv_full_alltalk 1
```

to knife.cfg.

I can't say exactly which cvars are necessary though, as Valve has added new cvars that I'm not up-to-date with.
