### ISSUE TITLE
Pug Record query website

### ISSUE THREAD

**Issue by 925916995** [splewis/csgo-pug-setup#388]
I'd like to ask if there is a website that can view the record of Pug's previous competition or download demo synchronously

**Comment by Sarthak001** [comment]
> I'd like to ask if there is a website that can view the record of Pug's previous competition or download demo synchronously

You can do it pretty easily , just host a http server or FTP server and put demo files in index folder of http server or FTP server

**Comment by splewis** [comment]
No, you'd have to find another plugin/website that adds those features.
