### ISSUE TITLE
Add Vertigo and Ancient to the Map Vote

### ISSUE THREAD

**Issue by BjarneBanane187** [splewis/csgo-pug-setup#389]
Hey there,
sorry if this has already been explained somewhere but I am unable to add Ancient and Vertigo to the Map Vote. I thought this would be done by changing the backupMaps in the maps.sp file but it doesn't seem to do anything. Any help would be appreciated.

**Comment by splewis** [comment]
The file you want to edit is `addons/sourcemod/configs/pugsetup/maps.txt`

I just updated its default to include more maps in https://github.com/splewis/csgo-pug-setup/commit/47744980d6c2cee8fb2be349ba0f294f5ab8515c
