### ISSUE TITLE
Missing File? And

### ISSUE THREAD

**Issue by vic-951** [splewis/csgo-pug-setup#395]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior
can´t find the file pugsetup.smx in 24fc6f9. In the install documentation are these steps:

From the download, you should have installed the following (to the csgo directory):

    addons/sourcemod/plugins/pugsetup.smx
    addons/sourcemod/translations/ (the entire directory)
    addons/sourcemod/configs/pugsetup/ (the entire directory)
    cfg/sourcemod/pugsetup (the entire directory)

but where can i find the first file?

and can I install the practicemod from splewis on the same server?

**Comment by vic-951** [comment]
oh sry i found it, you have do download it from the releases https://github.com/splewis/csgo-pug-setup/releases.

but still one question, can I install the practicemod and the pug on the same server?

**Comment by splewis** [comment]
>  can I install the practicemod and the pug on the same server?

Yes.
