### ISSUE TITLE
pugsetup.cfg and Knife rounds

### ISSUE THREAD

**Issue by lslima91** [splewis/csgo-pug-setup#40]
Hi, Good stuff!

I've been using your plugin. In order to use the knife round cvar I have to manually compile the .sp with the cvar='1' ? It seems to break the plugin when I do it.

Also, the pugsetup file is not generated.

lslima,

**Comment by splewis** [comment]
It's a new feature so you have to use a development build. Whether you compile it yourself or download a automated build from http://ci.splewis.net/job/csgo-pug-setup/lastSuccessfulBuild/ doesn't matter. You don't have to change the code though, it's a standard cvar.

cfg/sourcemod/pugsetup.cfg is always generated for me when the file doesn't exist. Are you looking in the regular cfg/ directory maybe?

**Comment by lslima91** [comment]
I didn't have right permissions for my server user -.- . Now it generates.

sm_pugsetup_default_knife_rounds "1"

Writing this on pugsetup.cfg is enough?

**Comment by splewis** [comment]
Yes. It's an option in the setup menu now as well, so you can enable/disable there regardless of the default value cvar.

**Comment by lslima91** [comment]
Everything seems ok now. Thanks :)

**Comment by nguyenbaodanh** [comment]
Hi Splewis! I love your pug plugin. Can you make a player stats website for
it ?

**Comment by splewis** [comment]
Sorry, I don't plan on adding a stats system anytime soon.

**Comment by nguyenbaodanh** [comment]
Please add . Like esea system. I'm willing to pay via paypal
