### ISSUE TITLE
Server crashes completely when trying to log in

### ISSUE THREAD

**Issue by Ferks-FK** [splewis/csgo-pug-setup#403]
### Expected behavior
When you log into the server, you should be able to log in normally and the server should remain "online".

### Actual behavior
Currently on a server running this plugin, when you log into the server, for some strange reason, the server crashes for no reason and restarts immediately afterwards.
It is important to say that the two servers tested in the video are totally similar.
The same plugins/extensions and settings were configured on these servers.
With the same sourcemod version.
The only difference is that pugsetup was active on one server and not on the other.
The error is completely random.
Sometimes everything works, sometimes everything stops all at once.

[Test Video](https://youtu.be/-vlzwl1iQeI)

### Steps to reproduce
Install the pugsetup plugin.
Try to log into the server.

- Plugin version: 2.0.7
- Sourcemod version: 1.10.0.6537
- OS: Linux

**Comment by sapphonie** [comment]
solved by `sm_pugsetup_use_game_warmup 0` or `sv_hibernate_when_empty 0`

**Comment by Ferks-FK** [comment]
Duplicate #368
