### ISSUE TITLE
Broked colors

### ISSUE THREAD

**Issue by echocage123** [splewis/csgo-pug-setup#405]
Not working colors in prefix

Based on the list of colors in the util.sp. Colors not showing
![image](https://user-images.githubusercontent.com/67440446/176905288-bec5a91f-4ab0-44ad-938a-e473d83b240f.png)
![image](https://user-images.githubusercontent.com/67440446/176906533-0e338ffb-21f7-474b-aaf7-04a76233cd26.png)
![image](https://user-images.githubusercontent.com/67440446/176905796-b321779b-9b73-4c64-9d7e-ac5058a1d601.png)

Info:
    Pug Setup 2.0.7

    SourceMod Version: 1.10.0.6545
    SourcePawn Engine: 1.10.0.6545, jit-x86 (build 1.10.0.6545)

    sm plugins list
      [SM] Listing 19 plugins:
    01 "Fun Votes" (1.10.0.6545) by AlliedModders LLC
    02 "Reserved Slots" (1.10.0.6545) by AlliedModders LLC
    03 "Basic Comm Control" (1.10.0.6545) by AlliedModders LLC
    04 "CS:GO PugSetup" (2.0.7) by splewis
    05 "Admin Menu" (1.10.0.6545) by AlliedModders LLC
    06 "Basic Commands" (1.10.0.6545) by AlliedModders LLC
    07 "Client Preferences" (1.10.0.6545) by AlliedModders LLC
    08 "Admin File Reader" (1.10.0.6545) by AlliedModders LLC
    09 "Basic Votes" (1.10.0.6545) by AlliedModders LLC
    10 "Anti-Flood" (1.10.0.6545) by AlliedModders LLC
    11 "PugSetup Switcher" (2.5) by Rolzzandik
    12 "Sound Commands" (1.10.0.6545) by AlliedModders LLC
    13 "Player Commands" (1.10.0.6545) by AlliedModders LLC
    14 "Basic Ban Commands" (1.10.0.6545) by AlliedModders LLC
    15 "Nextmap" (1.10.0.6545) by AlliedModders LLC
    16 "Fun Commands" (1.10.0.6545) by AlliedModders LLC
    17 "Admin Help" (1.10.0.6545) by AlliedModders LLC
    18 "Basic Info Triggers" (1.10.0.6545) by AlliedModders LLC
    19 "Basic Chat" (1.10.0.6545) by AlliedModders LLC
   sm exts list
    [SM] Displaying 9 extensions:
    [01] Automatic Updater (1.10.0.6545): Updates SourceMod gamedata files
    [02] Webternet (1.10.0.6545): Extension for interacting with URLs
    [03] CS Tools (1.10.0.6545): CS extended functionality
    [04] BinTools (1.10.0.6545): Low-level C/C++ Calling API
    [05] SDK Tools (1.10.0.6545): Source SDK Tools
    [06] Top Menus (1.10.0.6545): Creates sorted nested menus
    [07] <OPTIONAL> file "SteamWorks.ext.so": /home/server27968/game/csgo/addons/sourcemod/extensions/SteamWorks.ext.so: 
           cannot open shared object file: No such file or directory
    [08] Client Preferences (1.10.0.6545): Saves client preference settings
    [09] SQLite (1.10.0.6545): SQLite Driver

PS It seems that the creators do not care about this plugin and they do not respond

**Comment by splewis** [comment]
Hm, maybe a csgo update had changed what colors work, I'll take. a look.

> PS It seems that the creators do not care about this plugin and they do not respond

Bit of a strange complaint for an open source plugin anyone can contribute to. :)

**Comment by echocage123** [comment]
Thanks for the answer! And could you deal with the errors in the topic with Multi1v1? I created an issue there

**Comment by echocage123** [comment]
Sooooo?

**Comment by splewis** [comment]
`sm_pugsetup_message_prefix "{DARK_BLUE}[test]{LIGHT_GREEN}"` doesn't render as you expect since the first character cannot be a color code, unfortunately. I can't fix that, that's a [longtime](https://forums.alliedmods.net/showpost.php?p=2131459&postcount=12) csgo bug that I guess hasn't been fixed yet.

There might be workarounds, but typically I've put either a space or some other character (i.e. a `[` like the default does) first, before the color codes.
