### ISSUE TITLE
Cvar for buying more weapons in warmups

### ISSUE THREAD

**Issue by eyal282** [splewis/csgo-pug-setup#411]
sm_cvar mp_weapons_allow_typecount 9999

Literally unplayable. Splewis, pls fix.

**Comment by luan87us** [comment]
Just add mp_weapons_allow_typecount 9999 to the warmup.cfg file.

**Comment by eyal282** [comment]
> Just add mp_weapons_allow_typecount 9999 to the warmup.cfg file.

Not all people are programmers who know to locate cvars. There is no reason to keep it like it is currently.

**Comment by luan87us** [comment]
You don't need to be a programmer to do this though? 
It's just a simple server cfg command you can add to the warmup.cfg under /serverfiles/csgo/cfg/sourcemod/pugsetup.

**Comment by eyal282** [comment]
> You don't need to be a programmer to do this though? It's just a simple server cfg command you can add to the warmup.cfg under /serverfiles/csgo/cfg/sourcemod/pugsetup.

That's still not something most people will notice. I will end this discussion, and the rest is up to splewis.

**Comment by SanjaySRocks** [comment]
Fixed in #414
