### ISSUE TITLE
Error when i try to scramble the Teams 

### ISSUE THREAD

**Issue by mrcsdl** [splewis/csgo-pug-setup#419]
Hey Guys iam getting this error when i try to scramble the Teams 

[PugSetup] Scrambling the teams!
L 10/30/2022 - 13:12:09: [SM] Exception reported: Failed to lookup RoundRespawn signature.
L 10/30/2022 - 13:12:09: [SM] Blaming: pugsetup.smx
L 10/30/2022 - 13:12:09: [SM] Call stack trace:
L 10/30/2022 - 13:12:09: [SM]   [0] CS_RespawnPlayer
L 10/30/2022 - 13:12:09: [SM]   [1] Line 123, ./scripting/pugsetup/util.sp::SwitchPlayerTeam
L 10/30/2022 - 13:12:09: [SM]   [2] Line 1889, ./scripting/pugsetup.sp::ScrambleTeams
L 10/30/2022 - 13:12:09: [SM]   [3] Line 1859, ./scripting/pugsetup.sp::StartGame
L 10/30/2022 - 13:12:09: [SM]   [4] Line 1767, ./scripting/pugsetup.sp::Timer_CountDown

When i turn it off it works flawless

  1 "Basic Ban Commands" (1.10.0.6544) by AlliedModders LLC
  2 "Basic Commands" (1.10.0.6544) by AlliedModders LLC
  3 "Admin File Reader" (1.10.0.6544) by AlliedModders LLC
  4 "Admin Help" (1.10.0.6544) by AlliedModders LLC
  5 "Admin Menu" (1.10.0.6544) by AlliedModders LLC
  6 "Fun Commands" (1.10.0.6544) by AlliedModders LLC
  7 "CS:GO PugSetup" (2.0.7) by splewis

**Comment by splewis** [comment]
This is an issue with your sourcemod installation, probably the gamedata files. I would update it and the error should go away.
