### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by echocage123** [splewis/csgo-pug-setup#422]
PUG Setup is throwing error after loading boot (after game update) - 
> pugsetup.smx (CS:GO PugSetup): Required extension "cstrike" file("games/game.cstrike.ext") not running
pugsetup_switcher.smx (PugSetup Switcher): Could not find required plugin "pugsetup"
pugsetup_rollswitcher.smx: Could not find required plugin "pugsetup"
pugsetup_autokicker.smx (CS:GO PugSetup: autokicker): Required extension "cstrike" file("games/game.cstrike.ext") not running
highstats_alert.smx: Error detected in plugin startup (see error logs)
pugsetup_predictswitcher.smx: Could not find required plugin "pugsetup"
pugsetup_teamlocker.smx (CS:GO PugSetup: team locker): Required extension "cstrike" file("games/game.cstrike.ext") not running

SM Version:
> SourceMod 1.11.0.6916, by AlliedModders LLC
Server version

Server Version:
> Protocol version 13852 [1544/1544]
Exe version 1.38.5.2 (csgo)
Exe build: 11:38:53 Feb  2 2023 (8802) (730)
Windows version 6.2

[Pug Setup 2.0.7]

**Comment by mrc4tt** [comment]
@echocage123 You need to update the SourceMod =)

**Comment by echocage123** [comment]
@mrc4tt you are right, thanks for the reply
