### ISSUE TITLE
Adding mr30 to the selection menu

### ISSUE THREAD

**Issue by Mapettv** [splewis/csgo-pug-setup#427]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior

Button and function mr30

### Actual behavior

No access to mr30

### Steps to reproduce

Please note that "latest" is NOT a version! Run "sm plugins" in console to find out the exact plugin version.

- Plugin version:
- Sourcemod version:
- Steps to reproduce (please be specific):

**Comment by splewis** [comment]
Assuming by "mr30", you mean playing out all 30 rounds, you have to enable the option in a config file: https://github.com/splewis/csgo-pug-setup/blob/master/configs/pugsetup/setupoptions.cfg#L47-L51.

The file is stored in `addons/sourcemod/configs/pugsetup/setupoptions.cfg`

**Comment by Mapettv** [comment]
Thank you so much!
