### ISSUE TITLE
How to add skin plugin on server?

### ISSUE THREAD

**Issue by ElaSt1k** [splewis/csgo-pug-setup#429]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Steps to reproduce

Please note that "latest" is NOT a version! Run "sm plugins" in console to find out the exact plugin version.

- Plugin version:
- Sourcemod version:
- Steps to reproduce (please be specific):

**Comment by splewis** [comment]
I don't know, and it doesn't have anything to do with pugsetup.
