### ISSUE TITLE
Defuse kit greyed out for CTs

### ISSUE THREAD

**Issue by splewis** [splewis/csgo-pug-setup#44]
On rare occasions after team-swapping the defuse kit is greyed out (on the buywheel) for CT's.

Here is a screenshot: http://steamcommunity.com/id/splewis/screenshot/526128624943333840

(note that it even errors for a T here, the CTs see the same thing)

**Comment by splewis** [comment]
The largest obstacle to fixing this is getting a way to reproduce it. If anyone can manage to consistently reproduce this, the steps to do so would be very useful.

**Comment by Poheart** [comment]
Yes,this problem bothering me for long time and I'm using the oldest version

**Comment by splewis** [comment]
I've found what i believe is someone else's fix to this issue in Bara20's team mover plugin: https://github.com/Bara20/MoveCommands/blob/master/addons/sourcemod/scripting/movecommands.sp#L1442

**Comment by splewis** [comment]
Upon further investigation I think it might be unrelated to the team changes.

I have noticed it is seems to only happen (from my experience) after a map change - one possibility is tha something in the default warmup config might be causing it.

**Comment by Poheart** [comment]
Thanks for letting us know, the issue bothering us all and only some people can buy defuse kit..

**Comment by splewis** [comment]
For the record, anyone can still buy one using ``buy defuser`` in console (so buy binds still work).

**Comment by splewis** [comment]
A question for anyone experiencing this bug: are you using the team locker (pugsetup_teamlocker.smx) on your server? I suspect the issue lies with it.

**Comment by splewis** [comment]
I have a supposed fix pushed in the form of these 2 commits: https://github.com/splewis/csgo-pug-setup/commit/30d632f95ca6a6a1d7f13cee161fb1a9ff894ed5, https://github.com/splewis/csgo-pug-setup/commit/857a6b273e61fda9b36ad897b4615afbc579da9a

[Build 83](http://ci.splewis.net/job/csgo-pug-setup/83/) or later would contain them, if you want to test.

**Comment by encg** [comment]
I was using that plugin the one time we ran into this issue.

**Comment by splewis** [comment]
In the case the my previous attempt doesn't work, my plan is to fully eradicate any ``player_team`` event hooks, which includes [this one](https://github.com/splewis/csgo-pug-setup/blob/master/scripting/pugsetup.sp#L902), which I added to prevent drawing the teamchange notice in chat during team selection (via captains).

**Comment by mumixam** [comment]
Ive only seen it once and have only been using pugsetup.smx by itself
