### ISSUE TITLE
chataliases.cfg isnt read

### ISSUE THREAD

**Issue by mumixam** [splewis/csgo-pug-setup#49]
I was unable to get custom chat triggers to work in game so i added some `LogMessage()`'s to the code where chataliases.cfg is read and noticed some issues with reading the keyvalues. I fooled around with it but was unable to get it to traverse the keyvalues properly. I was also wonder why `kv.JumpToKey("maps")` is in there. I look forward to seeing your fix as ive spent too much time trying to get it work ;)

**Comment by splewis** [comment]
Wow, you're right, that "maps" jump definitely shouldn't be there. I'm not sure how I left something so broken in there, but I'll look into getting that fixed shortly.

KeyValues are definitely an annoying thing to debug sometimes too!

**Comment by splewis** [comment]
My completely untested fix: https://github.com/splewis/csgo-pug-setup/commit/8e0df2d676dea2bae1bc31a3453f96eaab9ff2d9

**Comment by splewis** [comment]
Tested my fix, it should work now.

**Comment by mumixam** [comment]
looks good thanks
