### ISSUE TITLE
fail

### ISSUE THREAD

**Issue by Joob** [splewis/csgo-pug-setup#52]
Hello,

Why give me this error

------

pugsetup.sp(26) : error 139: could not find type "ConVar"
pugsetup.sp(27) : error 139: could not find type "ConVar"
pugsetup.sp(28) : error 139: could not find type "ConVar"
pugsetup.sp(29) : error 139: could not find type "ConVar"
pugsetup.sp(30) : error 139: could not find type "ConVar"
pugsetup.sp(31) : error 139: could not find type "ConVar"
pugsetup.sp(32) : error 139: could not find type "ConVar"
pugsetup.sp(33) : error 139: could not find type "ConVar"
pugsetup.sp(34) : error 139: could not find type "ConVar"
pugsetup.sp(35) : error 139: could not find type "ConVar"
pugsetup.sp(36) : error 139: could not find type "ConVar"
pugsetup.sp(37) : error 139: could not find type "ConVar"
pugsetup.sp(38) : error 139: could not find type "ConVar"
pugsetup.sp(39) : error 139: could not find type "ConVar"
pugsetup.sp(40) : error 139: could not find type "ConVar"
pugsetup.sp(41) : error 139: could not find type "ConVar"
pugsetup.sp(42) : error 139: could not find type "ConVar"
pugsetup.sp(43) : error 139: could not find type "ConVar"
pugsetup.sp(44) : error 139: could not find type "ConVar"
pugsetup.sp(45) : error 139: could not find type "ConVar"
pugsetup.sp(46) : error 139: could not find type "ConVar"
pugsetup.sp(47) : error 139: could not find type "ConVar"
pugsetup.sp(48) : error 139: could not find type "ConVar"
pugsetup.sp(49) : error 139: could not find type "ConVar"
pugsetup.sp(50) : error 139: could not find type "ConVar"
pugsetup.sp(51) : error 139: could not find type "ConVar"

---------

I don't understand..

Regards,
Joob

**Comment by splewis** [comment]
You need to use the 1.7 compiler and include files.

**Comment by Joob** [comment]
yap.. I thought that had version 1.7 .. but now .. I put the 1.8 is nice.. Tks Splewis ;)
