### ISSUE TITLE
problem liveon3

### ISSUE THREAD

**Issue by Joob** [splewis/csgo-pug-setup#53]
Hello,

I have this errors when I compiled the file..

-----

pugsetup/liveon3.sp(3) : error 017: undefined symbol "g_InStartPhase"
pugsetup/liveon3.sp(6) : error 017: undefined symbol "g_hOnGoingLive"
pugsetup/liveon3.sp(11) : error 017: undefined symbol "IsPlayer"
pugsetup/liveon3.sp(12) : error 017: undefined symbol "UpdateClanTag"
pugsetup/liveon3.sp(16) : error 017: undefined symbol "g_hQuickRestarts"
pugsetup/liveon3.sp(18) : error 017: undefined symbol "PugSetupMessageToAll"
pugsetup/liveon3.sp(31) : error 017: undefined symbol "g_InStartPhase"
pugsetup/liveon3.sp(34) : error 017: undefined symbol "PugSetupMessageToAll"
pugsetup/liveon3.sp(42) : error 017: undefined symbol "g_InStartPhase"
pugsetup/liveon3.sp(45) : error 017: undefined symbol "PugSetupMessageToAll"
pugsetup/liveon3.sp(51) : error 017: undefined symbol "g_InStartPhase"
pugsetup/liveon3.sp(54) : error 017: undefined symbol "g_MatchLive"
pugsetup/liveon3.sp(54) : warning 215: expression has no effect
pugsetup/liveon3.sp(55) : error 017: undefined symbol "g_InStartPhase"
pugsetup/liveon3.sp(55) : warning 215: expression has no effect
pugsetup/liveon3.sp(56) : error 017: undefined symbol "g_hOnLive"
pugsetup/liveon3.sp(60) : error 017: undefined symbol "PugSetupMessageToAll"

-----

Regards,
Joob

**Comment by splewis** [comment]
That's because you're compiling a random file included by pugsetup. "liveon3.sp" isn't a plugin.

**Comment by Joob** [comment]
Sorry for the delay.. Oh nice, I'll try..
