### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by cheaamac** [splewis/csgo-pug-setup#62]
I have the same issue as the previous guy. I have everything that i have downloaded in the right folders but i dont seem to have the pugsetup.cfg

Im not really good with all this, any help would be wonderfull

Thanks

**Comment by splewis** [comment]
"previous guy" - not sure which guy you mean there

Anywho, check the error logs in ``csgo/addons/sourcemod/logs`` and post any you have. You should also check the sourcemod version just by typing ``sm`` in console while on the server.

**Comment by cheaamac** [comment]
SourceMod 1.6.4-dev+4608,
 
"
L 02/23/2015 - 19:24:27: Error log file session closed.
L 02/23/2015 - 19:49:59: SourceMod error session started
L 02/23/2015 - 19:49:59: Info (map "de_inferno") (file "errors_20150223.log")
"
thats all i am seeing ...

Is this any help?

**Comment by cheaamac** [comment]
And what i meant by previous guy i meant issue #61 sorry

**Comment by splewis** [comment]
Well you may not even have installed the plugin. Running ``sm plugins`` lists the plugins on the server.

Regardless, you need to update to sourcemod 1.7 to use the plugin. 

https://github.com/splewis/csgo-pug-setup#installation 
 "As of 1.3.0, sourcemod 1.7 is required."

**Comment by cheaamac** [comment]
ahhhhh i feel dumb, I thaught it was up to date.. not really good at this .. Its working good now man. thanks for all  your help :)
