### ISSUE TITLE
Change file hierarchy to csgo default file hierarchy 

### ISSUE THREAD

**Issue by jkroepke** [splewis/csgo-pug-setup#69]
Hi,

i prefer to extract a archiv 'as-is' without moving file around after extraction, like metamod and source archives.

Move follow files:
cfg/sourcemod/pugsetup -> csgo/cfg/sourcemod/pugsetup
configs/pugsetup -> csgo/addons/sourcemod/configs/pugsetup
scripting -> csgo/addons/sourcemod/scripting
translations -> csgo/addons/sourcemod/translations

With this it is easier to deploy servers with automation.

Cheers,
Jan

**Comment by splewis** [comment]
The directory structure of the source code shouldn't matter if you're actually using any of: a release, an automated build from http://ci.splewis.net, or the smbuild system I use to create those 2.

The releases also have the exact same structure as sourcemod archives (addons/ and cfg/ at the top level).

**Comment by jkroepke** [comment]
Hi,

I dont know about your ci server.

Thank you for the info.
