### ISSUE TITLE
map change , team swap vote and player color

### ISSUE THREAD

**Issue by DaNy3LL** [splewis/csgo-pug-setup#71]
Hello @splewis , I have some ideas/tweaks

First one is about map change : After the mapvote, if the voted map is the same as the current map, the map won't changed again. Eg : The current map is de_dust2 and the players vote for de_dust2. In this case the map won't be changed in de_dust2, because de_dust2 is the current map

Second one : After the knife round, start a vote for swap/stay. Sometimes players argue on staying/swapping teams so this would be useful ...

Third one : I noticed that sometimes, after randomizing teams, there are 2 players with the same color. What I mean by that ? By default each player should have a different color , to be easily distinguished by the teammates. If 2 players have the same color, it might be confusing sometimes.
![5632-radar](https://cloud.githubusercontent.com/assets/11727044/7137709/4bb8ac1c-e2c4-11e4-972c-d7032aa70085.png)

**Comment by splewis** [comment]
1) Eh, I can imagine some problems with not changing the map, but it''s not a bad idea

2) A good idea to have a cvar to make that possible 

3) Not sure if there's anything I can do. A possible workaround might be moving the players to spec then onto teams one at a time, though.

**Comment by splewis** [comment]
1) see https://github.com/splewis/csgo-pug-setup/issues/6
2) see https://github.com/splewis/csgo-pug-setup/issues/98
3) see https://github.com/splewis/csgo-pug-setup/issues/97
