### ISSUE TITLE
Demo directory

### ISSUE THREAD

**Issue by Nqk10** [splewis/csgo-pug-setup#75]
Hello, I have a server and I have a problem to find demo's directory. Before pug starts I setup the demo recorder on but when I see after the match I don't find any demo files.

Ps: This is a rent server and sorry for my bad english :(

**Comment by splewis** [comment]
The plugin just executes a ``tv_record`` command when the game starts, and that command records demoes to the game's root directory ``csgo``.

**Comment by Nqk10** [comment]
Yeah I know but I search every directory on the server and I couldn't find anywhere. I don't know if it's a issue on my plugin or it's the host problem

**Comment by splewis** [comment]
Then try doing ``tv_record`` manually and see if you can find the demo. If you can, it's the plugin's fault, and if you can't, it has nothing to do with the plugin.

**Comment by Nqk10** [comment]
So, I tried and says "GOTV not active". It's strange because I put these GOTV commands on server.cfg

**Comment by splewis** [comment]
Make sure you actually ran the command on the server (i.e. ``rcon tv_record``), not on your client.

**Comment by Nqk10** [comment]
Yes, I do exactly the same

**Comment by Nqk10** [comment]
Nvm, that rent host enables gotv on server when you pay like $4. Thanks for beeing supportive
