### ISSUE TITLE
Require ready up at half time. (Second warmup period, similar to cevo plugin)

### ISSUE THREAD

**Issue by mrmatthew2k** [splewis/csgo-pug-setup#77]
Instead of the second half starting immediately, allow for a second warmup period where each player needs to ready up again.

**Comment by splewis** [comment]
While I'm not opposed to cvar controlling if this is used, I'm not quite sure how the restoring of scores/stats is implemented by CEVO/ESEA. The only thing I can think of is the server just doing mp_restartgame commands and manually restoring the kills/assists/deaths/mvps separately, which doesn't seem like a very good solution.

**Comment by nongnoobjung** [comment]
or use pause timer when waiting switch team wait everyone ready and resume timer ? like ebot

**Comment by mrmatthew2k** [comment]
I barely know anything with sourcemod, but I think the score and individual player scores be easily restored through the individual round backup files, like "mp_backup_restore_load_file mp_backup_round_file_last".

So I imagine it would play out like this.
1. Halftime timer set to 0, so halftime instantly ends
2. 2nd half pistol round is in freezetime. Warmup config executed during freezetime.
3. Warmup period. Allow players to ready up.
4. Once all 10 players are ready use the command "mp_backup_round_file_last" to restore scores.

I might be oversimplifying this, though.

**Comment by ch4o5** [comment]
This should be even easier with this built-in cvar:
mp_halftime_pausetimer 1

Set this to 1 and it should pause automatically in halftime. Resume halftime timer with:
mp_halftime_pausetimer 0

;)

**Comment by splewis** [comment]
I won't be adding this, sorry.
