### ISSUE TITLE
suggestion save leaver money to new player connection

### ISSUE THREAD

**Issue by nongnoobjung** [splewis/csgo-pug-setup#78]
suggestion save leaver money to new player connection

when some player leaver from pug and new player connect replace slot leaver player it start with 800 gold can replace player get money equal leaver player ?

sry i'm bad english 

thank for consider

**Comment by splewis** [comment]
There's no guarantee a player leaving/joining is this simple - two players could leave, one could reconnect, then a different player reconnects from the original two - how much money would the new player get then?

Regardless, it doesn't make sense to worry about this for something intended for non-important games (even server plugins used for official matches don't do this).
