### ISSUE TITLE
teamlocker bug

### ISSUE THREAD

**Issue by nongnoobjung** [splewis/csgo-pug-setup#79]
teamlocker bug player still can join 6v5 6v6 when set pugmaxplayer 5v5

**Comment by splewis** [comment]
Hard to help much when I don't know which version you're using.

If it's a development build, you can try setting ``sm_pugsetup_debug 32``, starting a match, and reporting what gets logged to addons/sourcemod/logs/sm_pugsetup_debug.log

**Comment by nongnoobjung** [comment]
i'm use latest development  build i will try get log

**Comment by nongnoobjung** [comment]
new teamlocker work fine thankyou

**Comment by nongnoobjung** [comment]
addition report 

testing on 1v1 teamlocker workfine but when use on pug 5v5 teamlocker didn't block join team don't know why people on my server report this to me
