### ISSUE TITLE
Bug with pug leader.

### ISSUE THREAD

**Issue by JoniVR** [splewis/csgo-pug-setup#83]
Hello, thanks for this great plugin,

Currently I'm still experiencing a bug where the pug leader is not set correctly after finishing the setup process. I'ts on version 1.4.1 

Also, is it possible to add a bo3 map veto? If these 2 things can be done then it's just perfect!

Thanks for the hard work.

**Comment by splewis** [comment]
I've *hopefully* fixed it this time, you can test build 301 here if you'd like: http://ci.splewis.net/job/csgo-pug-setup/301/

BO3 vetoing is unlikely to happen, though.

**Comment by JoniVR** [comment]
ok thanks a lot!
