### ISSUE TITLE
[Suggestion] Auto Demo Upload (FTP)

### ISSUE THREAD

**Issue by SM9MB** [splewis/csgo-pug-setup#84]
Hello, it would be nice if you could add automatic demo uploading after each match.

Cheers.

**Comment by jkroepke** [comment]
If you have sime linux skils, you can use curlftpfs.

https://wiki.ubuntuusers.de/curlftpfs

Just mount the folder where the demo are saved.

**Comment by spot88** [comment]
This can be done with a easy bash script. 
#!/bin/bash
mv *.dem /var/www/***/GOTV/server1

**Comment by splewis** [comment]
I'm not going to directly support this. The fowards pugsetup provides can let another plugin do it.
