### ISSUE TITLE
Round and C4time Time

### ISSUE THREAD

**Issue by Duran8907** [splewis/csgo-pug-setup#86]
The config has the round time set to 1.75 which is 1:45 and the c4 timer set to 35 but when in the game its has 2 minute rounds and 45 seconds c4 timer. I was just wondering if I was doing something wrong.

**Comment by Duran8907** [comment]
Something else I am having a problem with is the bots are still spawning. How can I also fix this?

**Comment by splewis** [comment]
The plugin executes the config file in sm_pugsetup_live_cfg when the game starts (after executing the default game config: gamemode_competitive.cfg).

You're probably missing whatever file sm_pugsetup_live_cfg is pointing to. In 1.4.x, it would be cfg/sourcemod/pugsetup/live.cfg. Before that, it was named standard.cfg instead of live.cfg.

**Comment by Duran8907** [comment]
so was I suppose to leave those config files in a folder and upload them cause I just put them all in the cfg.sourcemod/live.cfg

**Comment by splewis** [comment]
You upload the addons/ and cfg/ directories into the server's csgo directory - that's it.

You should check
- what the value of ``sm_pugsetup_live_cfg`` is inside cfg/sourcemod/pugsetup/pugsetup.cfg
- then see if that file exists in the cfg/ directory

**Comment by Duran8907** [comment]
wait I don't put them in the source mod folders?

**Comment by splewis** [comment]
The download archives have 2 directories: addons and cfg. You upload each of these under the server's root csgo directory. That's it. Both should already exist, in which case you're just merging them.

**Comment by Duran8907** [comment]
ok so I don't put them in the sourcemod folders and I can just drag and drop the folders into the addon and cfg folders.

**Comment by Duran8907** [comment]
nvm got it fixed.
