### ISSUE TITLE
Damageprint format colors not working.

### ISSUE THREAD

**Issue by iDentity1337** [splewis/csgo-pug-setup#91]
So, I've tried many things, from adding colors.inc to adding the colors code itself into pugsetup_damageprint.sp and compiling it back, nothing worked. Can someone figure out why is damageprint format not working with colors like {DARK_BLUE} etc.

**Comment by splewis** [comment]
The pugsetup_damageprint addon did not support any coloring until [this commit](https://github.com/splewis/csgo-pug-setup/commit/49a2caa368b6384b938297e62b4d74d0678c0d88) 9 days ago, and isn't in a release yet.

**Comment by iDentity1337** [comment]
Well, I tried it now and it doesn't show the colorcode in chat ({DARK_BLUE}) any more, but still there is no color. But I understand it's in development, If there's no fix atm, I'll play with the code a bit and if I manage to make it work, I'll pull it here.

**Comment by splewis** [comment]
It works as far as I can tell since that commit. http://i.imgur.com/HhcvCwS.jpg

It should work since build 315 here: http://ci.splewis.net/job/csgo-pug-setup/315/

**Comment by iDentity1337** [comment]
Yeah, i redownloaded it and it works. Thank you so much. Great plugin ;)
