### ISSUE TITLE
team - map voteorder

### ISSUE THREAD

**Issue by keigel2001** [splewis/csgo-pug-setup#92]
Would it be possible to create an additional cvar **sm_pugsetup_voteorder**?
0 = vote for teams first, then maps
1 = mapvote first, then teams (default)

We often play with (random) captains pick players and captains veto maps, where it would be better to vote for the team first (then move players in teamspeak/mumble) and veto for maps then (teams can discuss with their captain).

**Comment by splewis** [comment]
Yes, but it would be tricky since the plugin would have to remember the teams across maps, which also makes it more fragile if a player leaves.

**Comment by splewis** [comment]
This won't be happening.
