### ISSUE TITLE
Stats for pugs

### ISSUE THREAD

**Issue by CodySmith** [splewis/csgo-pug-setup#93]
I would love you if you worked on a stats page for the pugs when using this plugin. The plugin works perfectly, though!

**Comment by splewis** [comment]
If one gets made, it probably won't come from myself. If it did, it would look terrible!

**Comment by latematt** [comment]
If splewis could make a plugin that communicates with a MySQL server with round statistics, I could write a simple implementation of that on a webserver and create a pull request. I'd need splewis (or anybody who can stand writing in the awful language called SourcePAWN) to write that plugin first.

**Comment by CodySmith** [comment]
If you guys actually do something like this, it would be incredible! For reference, look up sizziling stats. It's a server plugin for TF2 that is basically exactly what I'm imagining it to be like. Simple kda, and other interesting stats like bomb plants/defuses, hs ratio and stuff. Doesn't even need to be hosted on a website, a local html page that all the stats get shown on at the end of the match would be good. 

Ruby would make that fairly simple, right?

**Comment by splewis** [comment]
I'd actually prefer someone to make a web interface *separate* from this repository, given that I can't really help with it at all, and I'd prefer the two to be separate. I'd be fine to put a plugin in here that **only** touches MySQL tables. I'd have to think about what to store. If someone has suggestions for some ``CREATE TABLE`` statements, it'd help me out a lot.

**Comment by latematt** [comment]
A way you could go about doing this is creating tables for each pug, (you'd need to have a pugid type system in order to do this, probably not the best idea) one for player scoreboard (stats or whatever) and one for pug score.

**Comment by splewis** [comment]
I don't plan on adding this. Users can implement this on top of pugsetup if needed.
