### ISSUE TITLE
Enabling debug logging?

### ISSUE THREAD

**Issue by andersodt** [splewis/csgo-pug-setup#94]
Hey,

Been using this mod for awhile and just setup the RWS autobalancer. We just tried it in a game, but looking at the raw RWS it looked a little off (~70 vs ~50). 

I tried to look through the code, but it wasn't obvious to me how exactly the teams are supposed to be balanced, and I can't seem to find any output from the LogDebug statements. Do I have to turn debug logging on manually?

**Comment by splewis** [comment]
You'd have to manually set sm_pugsetup_debug to the sum of the values in this file: https://github.com/splewis/csgo-pug-setup/blob/master/scripting/include/logdebug.inc#L20

The balancing takes place [here](https://github.com/splewis/csgo-pug-setup/blob/master/scripting/pugsetup_rwsbalancer.sp#L141) and just alternates putting players on each team in descending rws order.

**Comment by andersodt** [comment]
Thanks. 

It seems like this sort of logic will create imbalanced teams much of the time. I might look into rewriting that balancing by keeping track of the team's RWS as it assigns players. So, the balancer would assign the next player to a team that has the lowest running RWS, instead of just alternating teams.

**Comment by splewis** [comment]
If you want to improve it, it'd be better to choose the optimize for the minimum difference in the average rws between teams (which, with equal team sizes is equivalent to optimizing the minimum in the sum of the players' rws).

A brute force approach over all possible teams isn't that bad with 10 choose 5 = 252 possibilities in the common case. I would've done it myself already, but generating all the possible teams is a bit cumbersome in sourcepawn.

**Comment by andersodt** [comment]
Any insight on how to do this permutation in Sourcepawn? I've tried to think about it for a bit but haven't come up with anything that makes sense.

**Comment by andersodt** [comment]
All right, well I hacked something together that solves this problem. It's really gross and ugly but it seems to work. I'll try to clean it up and pull request it.
