### ISSUE TITLE
Restarting Round

### ISSUE THREAD

**Issue by HalfEatenPie** [splewis/csgo-pug-setup#95]
Howdy!

First of all.  Love it thanks a ton for making this!  We use it to run our scrims and whatnot.

I've recently had an issue though.  I was hoping there was some kind of a way to fix this. 

If a user disconnects sometime in the middle of the round, we usually play it through but then .pause until the user reconnects.  After the user reconnects, he doesn't respawn until the next round.  So I was wondering if there was any way to restart the round (not the game) to get the person to respawn.

So far all Google searches are trying to point towards mp_restartgame, however that's not what we're looking for since that restarts the entire game and not just the round.

Thanks!

**Comment by splewis** [comment]
You could try setting ``mp_join_grace_time``. I'm not very familiar with that cvar, though.

**Comment by HalfEatenPie** [comment]
Hm true that is a possibility, however I was more thinking of a way to manually restart the round during pause since I'd rather not have the individual suddenly respawn when already half the team is already gone.

**Comment by splewis** [comment]
The overall design of the plugin is to be as non-invasive as possible to the non-vanilla game, and restarting the round is generally somewhat invasive, so it's unlikely to happen. Maybe utilizing round backups could happen as an admin/leader ability, though. I'll have to think about that. If it's easy I don't see any reason not to.

**Comment by HalfEatenPie** [comment]
Ahh gotcha!  I totally understand! 

If it could utilize round backups then that'd be fantastic.  I believe that's what many of the major pugs and such do for round restarts (with notification "Restored from backup_<etc>").  We've been having some good fun using this plugin, however this has been the only inconvenience we have.  

Thanks!

**Comment by andersodt** [comment]
This used to work (a user would spawn during paused freezetime) in an earlier version of the plugin (1.3) but since updating to the latest dev build, our pugs have also had issues of players not spawning during the freezetime or paused time. It looks like mp_join_grace_time is set to 2.5 -- perhaps I will try increasing it.

**Comment by splewis** [comment]
I would guess a csgo patch changed the behavior of respawning in freezetime and it wasn't the plugin.

The update 2 weeks ago seemed to subtly change spawning behavior, which causes issues for many others (notably, all ESEA metamod plugins completely being broken for several hours).

**Comment by encg** [comment]
We ran into this in one of our 10mans and were able to fix it by having the guy who disconnected join spectator then join his original team. He was alive after joining from spec.

**Comment by splewis** [comment]
That makes me suspect more that it's a game bug. I would guess you could reproduce this entirely without sourcemod (rcon mp_pause_match, then have someone reconnect).

I believe I could patch in stuff to make it work (by checking if in freezetime via the gamerules m_bFreezePeriod value, then hook the player_team event and respawn players in it when in freezetime), but that seems a bit dangerous. Maybe it'd work as a off-by-default cvar.
